/**
 * @file tiled_test.cpp
 * @brief Tests for Grapple::Tiled across all four language surfaces:
 *        the C API, the C++ RAII wrapper, and the Lua + Ruby bindings.
 *
 * The corpus (level.tmj, generated by scripts/gen_tiled_maps.py) has a
 * known layout, so tile GIDs and objects are asserted value-for-value.
 * VFS loading is proven by mounting maps.zip and loading by virtual path.
 */

#include <SDL3/SDL.h>
#include <grapple/bindings.h>
#include <grapple/lua.h>
#include <grapple/ruby.h>
#include <grapple/tiled.h>
#include <gtest/gtest.h>
#include <physfs.h>

#include <mruby/compile.h>
#include <mruby/string.h>

#include <string>

#include "grapple/tilemap.h"

#ifndef TILED_TEST_ASSETS_DIR
#error "TILED_TEST_ASSETS_DIR must be defined by the build"
#endif

namespace
{

std::string AssetPath(const char *name)
{
    return std::string(TILED_TEST_ASSETS_DIR) + "/" + name;
}

TEST(TiledC, ParsesGeneratedMapExactly)
{
    Grapple_TiledMap *map = Grapple_LoadTiledMap(AssetPath("level.tmj").c_str());
    ASSERT_NE(map, nullptr) << SDL_GetError();

    EXPECT_EQ(Grapple_TiledMapWidth(map), 8);
    EXPECT_EQ(Grapple_TiledMapHeight(map), 6);
    EXPECT_EQ(Grapple_TiledTileWidth(map), 16);
    EXPECT_EQ(Grapple_TiledTileHeight(map), 16);
    ASSERT_EQ(Grapple_TiledLayerCount(map), 3);
    EXPECT_STREQ(Grapple_TiledLayerName(map, 0), "ground");
    EXPECT_STREQ(Grapple_TiledLayerType(map, 2), "objectgroup");

    // ground[y][x] = 1 + (x + y) % 4 by construction.
    EXPECT_EQ(Grapple_TiledTileAt(map, 0, 0, 0), 1);
    EXPECT_EQ(Grapple_TiledTileAt(map, 0, 3, 2), 2);
    EXPECT_EQ(Grapple_TiledTileAt(map, 1, 2, 1), 5) << "decoration tile";
    EXPECT_EQ(Grapple_TiledTileAt(map, 1, 0, 0), 0) << "empty decoration";
    EXPECT_EQ(Grapple_TiledTileAt(map, 0, 99, 0), -1) << "out of range";
    EXPECT_EQ(Grapple_TiledTileAt(map, 7, 0, 0), -1) << "bad layer";

    ASSERT_EQ(Grapple_TiledObjectCount(map, 2), 2);
    Grapple_TiledObject obj;
    ASSERT_TRUE(Grapple_TiledObjectAt(map, 2, 0, &obj));
    EXPECT_STREQ(obj.name, "spawn");
    EXPECT_STREQ(obj.type, "player");
    EXPECT_FLOAT_EQ(obj.x, 24.0f);
    EXPECT_FALSE(Grapple_TiledObjectAt(map, 2, 9, &obj));

    ASSERT_NE(Grapple_TiledRaw(map), nullptr);
    Grapple_FreeTiledMap(map);
    Grapple_FreeTiledMap(nullptr); // safe no-op
}

TEST(TiledC, LoadsFromVfsZipArchive)
{
    ASSERT_TRUE(PHYSFS_init(nullptr));
    ASSERT_TRUE(PHYSFS_mount(AssetPath("maps.zip").c_str(), "/", 1));
    Grapple_TiledMap *map = Grapple_LoadTiledMap("level.tmj");
    ASSERT_NE(map, nullptr) << SDL_GetError();
    EXPECT_EQ(Grapple_TiledMapWidth(map), 8);
    Grapple_FreeTiledMap(map);
    PHYSFS_deinit();
}

TEST(TiledC, MalformedInputFailsCleanly)
{
    EXPECT_EQ(Grapple_LoadTiledMap("no-such-map.tmj"), nullptr);
    EXPECT_EQ(Grapple_LoadTiledMap(nullptr), nullptr);
    // Truncations of valid JSON must not crash the parser.
    size_t size = 0;
    char *json = static_cast<char *>(SDL_LoadFile(AssetPath("level.tmj").c_str(), &size));
    ASSERT_NE(json, nullptr);
    for (const double fraction : {0.1, 0.4, 0.8})
    {
        const std::string cut(json, static_cast<size_t>(static_cast<double>(size) * fraction));
        const std::string path = std::string(TILED_TEST_ASSETS_DIR) + "/truncated.tmj";
        ASSERT_TRUE(SDL_SaveFile(path.c_str(), cut.data(), cut.size()));
        Grapple_TiledMap *map = Grapple_LoadTiledMap(path.c_str());
        if (map != nullptr)
        {
            Grapple_FreeTiledMap(map);
        }
    }
    SDL_free(json);
    SDL_RemovePath((std::string(TILED_TEST_ASSETS_DIR) + "/truncated.tmj").c_str());
}

TEST(TiledCpp, RaiiWrapperMatchesCApi)
{
    grapple::Result<grapple::TiledMap> map = grapple::TiledMap::Load(AssetPath("level.tmj"));
    ASSERT_TRUE(map.ok()) << map.status().message();
    EXPECT_EQ(map->width(), 8);
    EXPECT_EQ(map->layer_count(), 3);
    EXPECT_EQ(map->LayerName(0).value_or(""), "ground");
    grapple::Result<int> gid = map->TileAt(0, 3, 2);
    ASSERT_TRUE(gid.ok());
    EXPECT_EQ(*gid, 2);
    EXPECT_FALSE(map->TileAt(9, 0, 0).ok());

    grapple::Result<grapple::TiledObject> spawn = map->ObjectAt(2, 0);
    ASSERT_TRUE(spawn.ok());
    EXPECT_EQ(spawn->name, "spawn");
    EXPECT_EQ(spawn->type, "player");

    grapple::Result<grapple::TiledMap> missing = grapple::TiledMap::Load("nope.tmj");
    EXPECT_FALSE(missing.ok());
    EXPECT_FALSE(missing.status().message().empty());

    // Move + drop under ASan proves the RAII cleanup.
    grapple::TiledMap owned = std::move(map).value();
    grapple::TiledMap moved = std::move(owned);
    (void)moved;
}

TEST(TiledLua, BindingsExposeTheMap)
{
    lua_State *L = Grapple_CreateLuaState();
    ASSERT_NE(L, nullptr);
    ASSERT_TRUE(Grapple_OpenLuaBindings(L));
    const std::string script =
        "local m = Grapple.load_map('" + AssetPath("level.tmj") + "')\n"
        "local w, h, tw, th = m:size()\n"
        "assert(w == 8 and h == 6 and tw == 16 and th == 16)\n"
        "assert(m:layers() == 3)\n"
        "assert(m:layer_name(0) == 'ground')\n"
        "assert(m:tile(0, 3, 2) == 2)\n"
        "assert(m:tile(1, 2, 1) == 5)\n"
        "local objs = m:objects(2)\n"
        "assert(#objs == 2 and objs[1].name == 'spawn' and objs[1].type == 'player')\n"
        "assert(objs[2].h == 32)\n"
        "m = nil; collectgarbage('collect'); collectgarbage('collect')\n";
    ASSERT_EQ(luaL_dostring(L, script.c_str()), LUA_OK) << lua_tostring(L, -1);
    lua_close(L);
}

TEST(TiledRuby, BindingsExposeTheMap)
{
    mrb_state *mrb = Grapple_CreateRubyState();
    ASSERT_NE(mrb, nullptr);
    ASSERT_TRUE(Grapple_OpenRubyBindings(mrb));
    const std::string script =
        "m = Grapple.load_map('" + AssetPath("level.tmj") + "')\n"
        "w, h, tw, th = m.size\n"
        "raise 'size' unless w == 8 && h == 6 && tw == 16 && th == 16\n"
        "raise 'layers' unless m.layers == 3\n"
        "raise 'name' unless m.layer_name(0) == 'ground'\n"
        "raise 'tile' unless m.tile(0, 3, 2) == 2\n"
        "objs = m.objects(2)\n"
        "raise 'objs' unless objs.length == 2 && objs[0][:name] == 'spawn'\n"
        "raise 'door' unless objs[1][:type] == 'door'\n"
        "m = nil\n"
        "GC.start\n";
    mrb_load_string(mrb, script.c_str());
    if (mrb->exc != nullptr)
    {
        mrb_value msg = mrb_inspect(mrb, mrb_obj_value(mrb->exc));
        FAIL() << RSTRING_CSTR(mrb, msg);
    }
    mrb_close(mrb);
}

} // namespace
