"""Script-facing API reference.

The script signature of a bound function is not always the C signature:
a (const void *data, size_t len) pair collapses into ONE argument, pure
out-parameters disappear from the argument list and come back as extra
return values, and destroy functions take ownership of their handle.
Nothing in a script tells the author this, so the generator writes the
resolved signatures out as bindings/generated/SCRIPT_API.md.
"""

from __future__ import annotations

from pathlib import Path

from .classify import TK, ScriptPlan
from .model import Manifest
from .spec import LIBRARIES


def _arg_type(pp) -> str:
    kind = pp.info.kind
    if pp.mode == "blob_in":
        return "string|nil"  # data+len collapsed
    if pp.mode == "mutstr_in":
        return "string"
    if kind == TK.STRING:
        return "string|nil"
    if kind == TK.HANDLE:
        return pp.info.base
    if kind == TK.POD:
        return f"{pp.info.base} table"
    if kind == TK.BOOL:
        return "boolean"
    if kind == TK.FLOAT:
        return "number"
    return "integer"


def _ret_type(info) -> str:
    kind = info.kind
    if kind == TK.BOOL:
        return "boolean"
    if kind == TK.FLOAT:
        return "number"
    if kind in (TK.STRING, TK.OWNED_STRING):
        return "string|nil"
    if kind == TK.HANDLE:
        return f"{info.base}|nil"
    if kind == TK.POD:
        return f"{info.base} table"
    if kind == TK.VOID:
        return ""
    return "integer"


def _signature(plan: ScriptPlan, name: str) -> tuple[str, str]:
    args: list[str] = []
    extra_returns: list[str] = []
    for pp in plan.params:
        if pp.mode == "pod_out":
            extra_returns.append(f"{pp.cname}: {pp.info.base} table")
            continue
        label = pp.cname or "arg"
        if pp.mode == "inout":
            args.append(f"{label}: {_arg_type(pp)}")
            extra_returns.append(f"{label}: {_arg_type(pp)}")
            continue
        args.append(f"{label}: {_arg_type(pp)}")
    rets: list[str] = []
    if plan.ret is not None:
        primary = _ret_type(plan.ret)
        if primary:
            rets.append(primary)
    rets.extend(extra_returns)
    return f"{name}({', '.join(args)})", ", ".join(rets) or "nil"


def emit_script_api(manifest: Manifest, outcomes: dict, repo: Path) -> None:
    lua = outcomes["lua"]
    lines: list[str] = []
    w = lines.append
    w("# Script API reference")
    w("")
    w("GENERATED by `python3 -m tools.bindgen` - DO NOT EDIT.")
    w("")
    w("Every function callable from Lua and Ruby, with the signature as the")
    w("**script** sees it. That is not always the C signature:")
    w("")
    w("- A `(const void *data, size_t len)` pair collapses into **one**")
    w("  string argument, so later parameters shift left. For example")
    w("  `Grapple_CreateGui(renderer, font_data, font_len, font_size)` is")
    w("  `GrappleC.CreateGui(renderer, font_data, font_size)` — passing a")
    w("  spurious length argument silently lands in `font_size`.")
    w("- Pure out-parameters are **not** arguments; they come back as extra")
    w("  return values, after the function's own return value.")
    w("- In/out parameters are passed *and* returned.")
    w("- `nk_bool` crosses as a real boolean; `0` is truthy in both")
    w("  languages, so test truthiness, never `== 1`.")
    w("")
    w("Ruby uses the same names and order (`SDL.CreateWindow`), with")
    w("constants as module constants (`SDL::INIT_VIDEO`) and multiple")
    w("returns as an array.")
    w("")
    for spec in LIBRARIES:
        plans = lua[spec.key]
        bound = {n: p for n, p in plans.items() if p.ok}
        if not bound:
            continue
        w(f"## {spec.title} — `{spec.script_module}`")
        w("")
        w("| Script call | Returns |")
        w("|---|---|")
        taken: set[str] = set()
        from .emit_lua import lua_name

        for cname in sorted(bound):
            script_name = lua_name(cname, spec.prefix, taken)
            sig, rets = _signature(bound[cname], f"{spec.script_module}.{script_name}")
            w(f"| `{sig}` | {rets} |")
        w("")
    (repo / "bindings" / "generated" / "SCRIPT_API.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )
