"""Coverage report: every parsed function accounted for on every surface."""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from .model import Manifest
from .spec import LIBRARIES


def emit_report(manifest: Manifest, outcomes: dict, repo: Path) -> None:
    cpp = outcomes["cpp"]
    lua = outcomes["lua"]
    lines: list[str] = []
    w = lines.append
    w("# Binding coverage")
    w("")
    w("GENERATED by `python3 -m tools.bindgen` - DO NOT EDIT.")
    w("")
    w("Every function parsed from the vendored headers is accounted for on")
    w("each surface. C++ never skips: functions become RAII factories,")
    w("methods, Status wrappers, or namespace aliases. Lua/Ruby share one")
    w("shape classifier, so their bound sets are identical; skipped")
    w("functions carry an explicit reason (callbacks, varargs, raw-memory")
    w("or threading APIs that have no place in scripts, unmarshalable")
    w("types). The full C API additionally stays reachable from C/C++.")
    w("")
    w("| Library | Functions | C++ raii | C++ status | C++ alias | Lua+Ruby bound | skipped |")
    w("|---|---|---|---|---|---|---|")
    tot = Counter()
    for spec in LIBRARIES:
        cplans = cpp[spec.key]
        splans = lua[spec.key]
        c = Counter(p.bucket for p in cplans.values())
        raii = c["factory"] + c["method"]
        bound = sum(1 for p in splans.values() if p.ok)
        skipped = len(splans) - bound
        n = len(manifest.libraries[spec.key].functions)
        w(f"| {spec.title} | {n} | {raii} | {c['status']} | {c['alias']} | {bound} | {skipped} |")
        tot.update({"n": n, "raii": raii, "status": c["status"],
                    "alias": c["alias"], "bound": bound, "skipped": skipped})
    w(f"| **Total** | {tot['n']} | {tot['raii']} | {tot['status']} | "
      f"{tot['alias']} | {tot['bound']} | {tot['skipped']} |")
    w("")
    w("## Script-surface skip reasons")
    w("")
    reasons: Counter = Counter()
    for spec in LIBRARIES:
        for p in lua[spec.key].values():
            if not p.ok:
                reasons[_bucket_reason(p.reason)] += 1
    for reason, count in reasons.most_common():
        w(f"- {count}: {reason}")
    w("")
    w("## Per-library skipped functions")
    w("")
    for spec in LIBRARIES:
        skipped = {n: p.reason for n, p in lua[spec.key].items() if not p.ok}
        if not skipped:
            continue
        w(f"<details><summary>{spec.title} ({len(skipped)})</summary>")
        w("")
        for name in sorted(skipped):
            w(f"- `{name}` — {skipped[name]}")
        w("")
        w("</details>")
        w("")
    (repo / "modules" / "bindings" / "generated" / "COVERAGE.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


def _bucket_reason(reason: str) -> str:
    if reason.startswith("param") and "<funcptr>" in reason:
        return "callback parameter"
    if "funcptr" in reason:
        return "callback parameter"
    if reason.startswith("param"):
        return "unmarshalable parameter type"
    if reason.startswith("return type"):
        return "unmarshalable return type"
    if reason.startswith("returns struct pointer"):
        return "unmarshalable return type"
    return reason
