/*
 * This file is loading the irep
 * Ruby GEM code.
 *
 * This file was generated by mruby/lib/mruby/gem.rb.
 *
 * IMPORTANT:
 *   This file was generated!
 *   All manual changes will get lost.
 */
#include <stdlib.h>
#include <mruby.h>
#include <mruby/irep.h>
#include <mruby/debug.h>
#include <mruby/proc.h>

#define mrb_BRACED(...) {__VA_ARGS__}
#define mrb_DEFINE_SYMS_VAR(name, len, syms, qualifier) \
  static qualifier mrb_sym name[len] = mrb_BRACED syms

mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_22, 2, (MRB_SYM_Q(has_key), MRB_SYM(call), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_22[66] = {
0x39,0x04,0x00,0x00,0x12,0x04,0x01,0x05,0x01,0x01,0x07,0x01,0x2f,0x06,0x00,0x01,0x28,0x06,0x00,0x1e,
0x21,0x06,0x03,0x00,0x01,0x07,0x01,0x12,0x08,0x01,0x09,0x01,0x23,0x08,0x21,0x09,0x06,0x00,0x01,0x0a,
0x01,0x23,0x09,0x32,0x06,0x01,0x03,0x26,0x00,0x09,0x21,0x06,0x06,0x00,0x01,0x07,0x01,0x23,0x06,0x01,
0x03,0x06,0x25,0x04,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_22, 2, (MRB_SYM(k), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_22 = {
  3,12,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_22,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_22,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_22,
  NULL,					/* debug_info */
  66,0,2,0,0
};
static const mrb_irep *gem_mrblib_mruby_hash_ext_proc_reps_2[1] = {
  &gem_mrblib_mruby_hash_ext_proc_irep_22,
};
static const mrb_irep_pool gem_mrblib_mruby_hash_ext_proc_pool_2[2] = {
{IREP_TT_SSTR|(15<<2), {"\x48\x61\x73\x68\x20\x72\x65\x71\x75\x69\x72\x65\x64\x20\x28"}},
{IREP_TT_SSTR|(7<<2), {"\x20\x67\x69\x76\x65\x6e\x29"}},
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_2, 8, (MRB_SYM(size), MRB_SYM(__merge), MRB_SYM(Hash), MRB_OPSYM(eqq), MRB_SYM(TypeError), MRB_SYM(class), MRB_SYM(raise), MRB_SYM(each_key), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_2[117] = {
0x39,0x00,0x10,0x01,0x01,0x03,0x02,0x06,0x04,0x01,0x07,0x01,0x33,0x07,0x00,0x01,0x05,0x07,0x01,0x07,
0x03,0x27,0x07,0x00,0x0d,0x11,0x08,0x01,0x09,0x01,0x54,0x08,0x2f,0x07,0x01,0x0f,0x3d,0x07,0x01,0x07,
0x04,0x01,0x08,0x05,0x4e,0x07,0x28,0x07,0x00,0x42,0x00,0x01,0x07,0x01,0x01,0x08,0x04,0x23,0x07,0x01,
0x06,0x07,0x49,0x04,0x07,0x01,0x1d,0x07,0x02,0x01,0x08,0x06,0x32,0x07,0x03,0x01,0x27,0x07,0x00,0x17,
0x1d,0x08,0x04,0x5c,0x09,0x00,0x01,0x0a,0x06,0x33,0x0a,0x05,0x5d,0x09,0x5c,0x0a,0x01,0x5d,0x09,0x2f,
0x07,0x06,0x02,0x01,0x07,0x06,0x62,0x08,0x00,0x34,0x07,0x07,0x00,0x26,0xff,0xb2,0x3f,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_2, 6, (MRB_SYM(others), 0,MRB_SYM(block), MRB_SYM(i), MRB_SYM(len), MRB_SYM(other), ), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_2 = {
  7,12,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_2,
  gem_mrblib_mruby_hash_ext_proc_pool_2,gem_mrblib_mruby_hash_ext_proc_syms_2,gem_mrblib_mruby_hash_ext_proc_reps_2,
  gem_mrblib_mruby_hash_ext_proc_lv_2,
  NULL,					/* debug_info */
  117,2,8,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_3, 1, (MRB_SYM(__compact), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_3[9] = {
0x39,0x00,0x00,0x00,0x30,0x02,0x00,0x3d,0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_3, 1, (0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_3 = {
  2,4,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_3,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_3,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_3,
  NULL,					/* debug_info */
  9,0,1,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_4, 2, (MRB_SYM(dup), MRB_SYM(__compact), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_4[18] = {
0x39,0x00,0x00,0x00,0x30,0x03,0x00,0x01,0x02,0x03,0x01,0x03,0x02,0x33,0x03,0x01,0x3d,0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_4, 2, (0,MRB_SYM(h), ), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_4 = {
  3,5,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_4,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_4,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_4,
  NULL,					/* debug_info */
  18,0,2,0,0
};
static const mrb_irep_pool gem_mrblib_mruby_hash_ext_proc_pool_5[2] = {
{IREP_TT_SSTR|(15<<2), {"\x4b\x65\x79\x20\x6e\x6f\x74\x20\x66\x6f\x75\x6e\x64\x3a\x20"}},
{IREP_TT_SSTR|(0<<2), {""}},
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_5, 8, (MRB_SYM(NONE), MRB_SYM_Q(key), MRB_SYM(call), MRB_SYM_Q(equal), MRB_OPSYM(not), MRB_SYM(KeyError), MRB_SYM(inspect), MRB_SYM(raise), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_5[105] = {
0x39,0x04,0x20,0x01,0x26,0x00,0x03,0x26,0x00,0x03,0x1d,0x02,0x00,0x01,0x04,0x03,0x01,0x06,0x01,0x2f,
0x05,0x01,0x01,0x28,0x05,0x00,0x0a,0x12,0x05,0x01,0x06,0x01,0x23,0x05,0x26,0x00,0x42,0x01,0x05,0x04,
0x28,0x05,0x00,0x0d,0x01,0x05,0x04,0x01,0x06,0x01,0x32,0x05,0x02,0x01,0x26,0x00,0x2e,0x1d,0x05,0x00,
0x01,0x06,0x02,0x32,0x05,0x03,0x01,0x33,0x05,0x04,0x28,0x05,0x00,0x06,0x01,0x05,0x02,0x26,0x00,0x17,
0x1d,0x06,0x05,0x5c,0x07,0x00,0x01,0x08,0x01,0x33,0x08,0x06,0x5d,0x07,0x5c,0x08,0x01,0x5d,0x07,0x2f,
0x05,0x07,0x02,0x3d,0x05,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_5, 4, (MRB_SYM(key), MRB_SYM(none), 0,MRB_SYM(block), ), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_5 = {
  5,10,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_5,
  gem_mrblib_mruby_hash_ext_proc_pool_5,gem_mrblib_mruby_hash_ext_proc_syms_5,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_5,
  NULL,					/* debug_info */
  105,2,8,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_103, 2, (MRB_SYM(call), MRB_SYM(delete), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_103[36] = {
0x39,0x08,0x00,0x00,0x21,0x04,0x02,0x00,0x01,0x05,0x01,0x01,0x06,0x02,0x32,0x04,0x00,0x02,0x28,0x04,
0x00,0x0a,0x01,0x05,0x01,0x2f,0x04,0x01,0x01,0x26,0x00,0x02,0x11,0x04,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_103, 3, (MRB_SYM(k), MRB_SYM(v), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_103 = {
  4,8,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_103,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_103,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_103,
  NULL,					/* debug_info */
  36,0,2,0,0
};
static const mrb_irep *gem_mrblib_mruby_hash_ext_proc_reps_6[1] = {
  &gem_mrblib_mruby_hash_ext_proc_irep_103,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_6, 3, (MRB_SYM(delete_if), MRB_SYM(to_enum), MRB_SYM(each), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_6[31] = {
0x39,0x00,0x00,0x01,0x01,0x02,0x01,0x01,0x03,0x02,0x27,0x03,0x00,0x09,0x10,0x04,0x00,0x2f,0x03,0x01,
0x01,0x3d,0x03,0x62,0x04,0x00,0x31,0x03,0x02,0x00,0x3f,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_6, 2, (0,MRB_SYM(block), ), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_6 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_6,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_6,gem_mrblib_mruby_hash_ext_proc_reps_6,
  gem_mrblib_mruby_hash_ext_proc_lv_6,
  NULL,					/* debug_info */
  31,0,3,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_7, 2, (MRB_SYM(to_a), MRB_SYM(flatten), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_7[24] = {
0x39,0x00,0x20,0x00,0x26,0x00,0x03,0x26,0x00,0x02,0x07,0x01,0x30,0x03,0x00,0x01,0x04,0x01,0x32,0x03,
0x01,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_7, 2, (MRB_SYM(level), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_7 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_7,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_7,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_7,
  NULL,					/* debug_info */
  24,0,2,0,0
};
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_144[21] = {
0x39,0x08,0x00,0x00,0x21,0x05,0x02,0x00,0x01,0x06,0x02,0x01,0x07,0x01,0x01,0x04,0x07,0x25,0x05,0x3d,
0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_144, 3, (MRB_SYM(k), MRB_SYM(v), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_144 = {
  4,9,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_144,
  NULL,NULL,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_144,
  NULL,					/* debug_info */
  21,0,0,0,0
};
static const mrb_irep *gem_mrblib_mruby_hash_ext_proc_reps_8[1] = {
  &gem_mrblib_mruby_hash_ext_proc_irep_144,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_8, 3, (MRB_SYM(class), MRB_SYM(new), MRB_SYM(each), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_8[22] = {
0x39,0x00,0x00,0x00,0x30,0x03,0x00,0x33,0x03,0x01,0x01,0x02,0x03,0x62,0x04,0x00,0x31,0x03,0x02,0x00,
0x3d,0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_8, 2, (0,MRB_SYM(h), ), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_8 = {
  3,5,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_8,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_8,gem_mrblib_mruby_hash_ext_proc_reps_8,
  gem_mrblib_mruby_hash_ext_proc_lv_8,
  NULL,					/* debug_info */
  22,0,3,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_165, 2, (MRB_SYM(call), MRB_SYM(delete), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_165[39] = {
0x39,0x08,0x00,0x00,0x21,0x04,0x02,0x00,0x01,0x05,0x01,0x01,0x06,0x02,0x52,0x05,0x02,0x32,0x04,0x00,
0x01,0x28,0x04,0x00,0x05,0x11,0x04,0x26,0x00,0x07,0x01,0x05,0x01,0x2f,0x04,0x01,0x01,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_165, 3, (MRB_SYM(k), MRB_SYM(v), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_165 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_165,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_165,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_165,
  NULL,					/* debug_info */
  39,0,2,0,0
};
static const mrb_irep *gem_mrblib_mruby_hash_ext_proc_reps_9[1] = {
  &gem_mrblib_mruby_hash_ext_proc_irep_165,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_9, 3, (MRB_SYM(keep_if), MRB_SYM(to_enum), MRB_SYM(each), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_9[31] = {
0x39,0x00,0x00,0x01,0x01,0x02,0x01,0x01,0x03,0x02,0x27,0x03,0x00,0x09,0x10,0x04,0x00,0x2f,0x03,0x01,
0x01,0x3d,0x03,0x62,0x04,0x00,0x31,0x03,0x02,0x00,0x3f,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_9, 2, (0,MRB_SYM(block), ), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_9 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_9,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_9,gem_mrblib_mruby_hash_ext_proc_reps_9,
  gem_mrblib_mruby_hash_ext_proc_lv_9,
  NULL,					/* debug_info */
  31,0,3,1,0
};
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_10[5] = {
0x39,0x00,0x00,0x00,0x3f,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_10, 1, (0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_10 = {
  2,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_10,
  NULL,NULL,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_10,
  NULL,					/* debug_info */
  5,0,0,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_206, 1, (MRB_SYM_Q(key), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_206[35] = {
0x39,0x08,0x00,0x00,0x21,0x04,0x01,0x00,0x01,0x05,0x01,0x32,0x04,0x00,0x01,0x28,0x04,0x00,0x0e,0x21,
0x04,0x01,0x00,0x01,0x05,0x01,0x23,0x04,0x01,0x05,0x02,0x4d,0x04,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_206, 3, (MRB_SYM(key), MRB_SYM(val), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_206 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_206,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_206,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_206,
  NULL,					/* debug_info */
  35,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_hash_ext_proc_reps_11[1] = {
  &gem_mrblib_mruby_hash_ext_proc_irep_206,
};
static const mrb_irep_pool gem_mrblib_mruby_hash_ext_proc_pool_11[2] = {
{IREP_TT_SSTR|(14<<2), {"\x63\x61\x6e\x27\x74\x20\x63\x6f\x6e\x76\x65\x72\x74\x20"}},
{IREP_TT_SSTR|(8<<2), {"\x20\x74\x6f\x20\x48\x61\x73\x68"}},
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_11, 7, (MRB_SYM(Hash), MRB_OPSYM(eqq), MRB_SYM(TypeError), MRB_SYM(class), MRB_SYM(raise), MRB_SYM(size), MRB_SYM_Q(all), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_11[65] = {
0x39,0x04,0x00,0x00,0x1d,0x03,0x00,0x01,0x04,0x01,0x32,0x03,0x01,0x01,0x27,0x03,0x00,0x17,0x1d,0x04,
0x02,0x5c,0x05,0x00,0x01,0x06,0x01,0x33,0x06,0x03,0x5d,0x05,0x5c,0x06,0x01,0x5d,0x05,0x2f,0x03,0x04,
0x02,0x30,0x03,0x05,0x01,0x04,0x01,0x33,0x04,0x05,0x4e,0x03,0x28,0x03,0x00,0x07,0x62,0x04,0x00,0x31,
0x03,0x06,0x00,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_11, 2, (MRB_SYM(hash), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_11 = {
  3,8,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_11,
  gem_mrblib_mruby_hash_ext_proc_pool_11,gem_mrblib_mruby_hash_ext_proc_syms_11,gem_mrblib_mruby_hash_ext_proc_reps_11,
  gem_mrblib_mruby_hash_ext_proc_lv_11,
  NULL,					/* debug_info */
  65,2,7,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_227, 1, (MRB_SYM_Q(key), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_227[35] = {
0x39,0x08,0x00,0x00,0x21,0x04,0x01,0x00,0x01,0x05,0x01,0x32,0x04,0x00,0x01,0x28,0x04,0x00,0x0e,0x21,
0x04,0x01,0x00,0x01,0x05,0x01,0x23,0x04,0x01,0x05,0x02,0x4d,0x04,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_227, 3, (MRB_SYM(key), MRB_SYM(val), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_227 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_227,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_227,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_227,
  NULL,					/* debug_info */
  35,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_hash_ext_proc_reps_12[1] = {
  &gem_mrblib_mruby_hash_ext_proc_irep_227,
};
static const mrb_irep_pool gem_mrblib_mruby_hash_ext_proc_pool_12[2] = {
{IREP_TT_SSTR|(14<<2), {"\x63\x61\x6e\x27\x74\x20\x63\x6f\x6e\x76\x65\x72\x74\x20"}},
{IREP_TT_SSTR|(8<<2), {"\x20\x74\x6f\x20\x48\x61\x73\x68"}},
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_12, 7, (MRB_SYM(Hash), MRB_OPSYM(eqq), MRB_SYM(TypeError), MRB_SYM(class), MRB_SYM(raise), MRB_SYM(size), MRB_SYM_Q(all), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_12[65] = {
0x39,0x04,0x00,0x00,0x1d,0x03,0x00,0x01,0x04,0x01,0x32,0x03,0x01,0x01,0x27,0x03,0x00,0x17,0x1d,0x04,
0x02,0x5c,0x05,0x00,0x01,0x06,0x01,0x33,0x06,0x03,0x5d,0x05,0x5c,0x06,0x01,0x5d,0x05,0x2f,0x03,0x04,
0x02,0x30,0x03,0x05,0x01,0x04,0x01,0x33,0x04,0x05,0x4f,0x03,0x28,0x03,0x00,0x07,0x62,0x04,0x00,0x31,
0x03,0x06,0x00,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_12, 2, (MRB_SYM(hash), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_12 = {
  3,8,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_12,
  gem_mrblib_mruby_hash_ext_proc_pool_12,gem_mrblib_mruby_hash_ext_proc_syms_12,gem_mrblib_mruby_hash_ext_proc_reps_12,
  gem_mrblib_mruby_hash_ext_proc_lv_12,
  NULL,					/* debug_info */
  65,2,7,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_248, 1, (MRB_SYM_Q(key), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_248[29] = {
0x39,0x08,0x00,0x00,0x01,0x05,0x01,0x2f,0x04,0x00,0x01,0x28,0x04,0x00,0x0c,0x12,0x04,0x01,0x05,0x01,
0x23,0x04,0x01,0x05,0x02,0x4d,0x04,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_248, 3, (MRB_SYM(key), MRB_SYM(val), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_248 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_248,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_248,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_248,
  NULL,					/* debug_info */
  29,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_hash_ext_proc_reps_13[1] = {
  &gem_mrblib_mruby_hash_ext_proc_irep_248,
};
static const mrb_irep_pool gem_mrblib_mruby_hash_ext_proc_pool_13[2] = {
{IREP_TT_SSTR|(14<<2), {"\x63\x61\x6e\x27\x74\x20\x63\x6f\x6e\x76\x65\x72\x74\x20"}},
{IREP_TT_SSTR|(8<<2), {"\x20\x74\x6f\x20\x48\x61\x73\x68"}},
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_13, 7, (MRB_SYM(Hash), MRB_OPSYM(eqq), MRB_SYM(TypeError), MRB_SYM(class), MRB_SYM(raise), MRB_SYM(size), MRB_SYM_Q(all), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_13[68] = {
0x39,0x04,0x00,0x00,0x1d,0x03,0x00,0x01,0x04,0x01,0x32,0x03,0x01,0x01,0x27,0x03,0x00,0x17,0x1d,0x04,
0x02,0x5c,0x05,0x00,0x01,0x06,0x01,0x33,0x06,0x03,0x5d,0x05,0x5c,0x06,0x01,0x5d,0x05,0x2f,0x03,0x04,
0x02,0x30,0x03,0x05,0x01,0x04,0x01,0x33,0x04,0x05,0x50,0x03,0x28,0x03,0x00,0x0a,0x01,0x03,0x01,0x62,
0x04,0x00,0x34,0x03,0x06,0x00,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_13, 2, (MRB_SYM(hash), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_13 = {
  3,8,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_13,
  gem_mrblib_mruby_hash_ext_proc_pool_13,gem_mrblib_mruby_hash_ext_proc_syms_13,gem_mrblib_mruby_hash_ext_proc_reps_13,
  gem_mrblib_mruby_hash_ext_proc_lv_13,
  NULL,					/* debug_info */
  68,2,7,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_269, 1, (MRB_SYM_Q(key), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_269[29] = {
0x39,0x08,0x00,0x00,0x01,0x05,0x01,0x2f,0x04,0x00,0x01,0x28,0x04,0x00,0x0c,0x12,0x04,0x01,0x05,0x01,
0x23,0x04,0x01,0x05,0x02,0x4d,0x04,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_269, 3, (MRB_SYM(key), MRB_SYM(val), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_269 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_269,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_269,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_269,
  NULL,					/* debug_info */
  29,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_hash_ext_proc_reps_14[1] = {
  &gem_mrblib_mruby_hash_ext_proc_irep_269,
};
static const mrb_irep_pool gem_mrblib_mruby_hash_ext_proc_pool_14[2] = {
{IREP_TT_SSTR|(14<<2), {"\x63\x61\x6e\x27\x74\x20\x63\x6f\x6e\x76\x65\x72\x74\x20"}},
{IREP_TT_SSTR|(8<<2), {"\x20\x74\x6f\x20\x48\x61\x73\x68"}},
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_14, 7, (MRB_SYM(Hash), MRB_OPSYM(eqq), MRB_SYM(TypeError), MRB_SYM(class), MRB_SYM(raise), MRB_SYM(size), MRB_SYM_Q(all), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_14[68] = {
0x39,0x04,0x00,0x00,0x1d,0x03,0x00,0x01,0x04,0x01,0x32,0x03,0x01,0x01,0x27,0x03,0x00,0x17,0x1d,0x04,
0x02,0x5c,0x05,0x00,0x01,0x06,0x01,0x33,0x06,0x03,0x5d,0x05,0x5c,0x06,0x01,0x5d,0x05,0x2f,0x03,0x04,
0x02,0x30,0x03,0x05,0x01,0x04,0x01,0x33,0x04,0x05,0x51,0x03,0x28,0x03,0x00,0x0a,0x01,0x03,0x01,0x62,
0x04,0x00,0x34,0x03,0x06,0x00,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_14, 2, (MRB_SYM(hash), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_14 = {
  3,8,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_14,
  gem_mrblib_mruby_hash_ext_proc_pool_14,gem_mrblib_mruby_hash_ext_proc_syms_14,gem_mrblib_mruby_hash_ext_proc_reps_14,
  gem_mrblib_mruby_hash_ext_proc_lv_14,
  NULL,					/* debug_info */
  68,2,7,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_15, 2, (MRB_SYM(size), MRB_SYM(dig), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_15[57] = {
0x39,0x04,0x10,0x00,0x12,0x05,0x01,0x06,0x01,0x23,0x05,0x01,0x04,0x05,0x01,0x05,0x02,0x33,0x05,0x00,
0x06,0x06,0x50,0x05,0x28,0x05,0x00,0x18,0x01,0x05,0x04,0x01,0x06,0x05,0x29,0x06,0x00,0x0b,0x11,0x06,
0x01,0x07,0x02,0x54,0x06,0x32,0x05,0x01,0x0f,0x26,0x00,0x03,0x01,0x05,0x04,0x3d,0x05,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_15, 4, (MRB_SYM(idx), MRB_SYM(args), 0,MRB_SYM(n), ), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_15 = {
  5,8,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_15,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_15,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_15,
  NULL,					/* debug_info */
  57,0,2,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_310, 1, (MRB_SYM(call), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_310[39] = {
0x39,0x04,0x00,0x00,0x21,0x04,0x02,0x00,0x01,0x05,0x01,0x32,0x04,0x00,0x01,0x01,0x03,0x04,0x21,0x05,
0x03,0x00,0x01,0x06,0x03,0x12,0x07,0x01,0x08,0x01,0x23,0x07,0x01,0x04,0x07,0x25,0x05,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_310, 3, (MRB_SYM(k), 0,MRB_SYM(new_key), ), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_310 = {
  4,10,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_310,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_310,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_310,
  NULL,					/* debug_info */
  39,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_hash_ext_proc_reps_16[1] = {
  &gem_mrblib_mruby_hash_ext_proc_irep_310,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_16, 4, (MRB_SYM(transform_keys), MRB_SYM(to_enum), MRB_SYM(keys), MRB_SYM(each), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_16[38] = {
0x39,0x00,0x00,0x01,0x01,0x02,0x01,0x01,0x04,0x02,0x27,0x04,0x00,0x09,0x10,0x05,0x00,0x2f,0x04,0x01,
0x01,0x3d,0x04,0x5e,0x03,0x00,0x30,0x04,0x02,0x62,0x05,0x00,0x34,0x04,0x03,0x00,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_16, 3, (0,MRB_SYM(block), MRB_SYM(hash), ), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_16 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_16,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_16,gem_mrblib_mruby_hash_ext_proc_reps_16,
  gem_mrblib_mruby_hash_ext_proc_lv_16,
  NULL,					/* debug_info */
  38,0,4,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_17, 4, (MRB_SYM_B(transform_keys), MRB_SYM(to_enum), MRB_SYM(transform_keys), MRB_SYM(replace), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_17[41] = {
0x39,0x00,0x00,0x01,0x01,0x02,0x01,0x01,0x04,0x02,0x27,0x04,0x00,0x09,0x10,0x05,0x00,0x2f,0x04,0x01,
0x01,0x3d,0x04,0x01,0x05,0x02,0x31,0x04,0x02,0x00,0x01,0x03,0x04,0x01,0x05,0x03,0x2f,0x04,0x03,0x01,
0x3f,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_17, 3, (0,MRB_SYM(block), MRB_SYM(hash), ), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_17 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_17,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_17,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_17,
  NULL,					/* debug_info */
  41,0,4,0,0
};
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_351[32] = {
0x39,0x04,0x00,0x00,0x21,0x04,0x03,0x00,0x01,0x05,0x01,0x12,0x07,0x01,0x08,0x01,0x23,0x07,0x44,0x06,
0x00,0x01,0x36,0x06,0x01,0x01,0x03,0x06,0x25,0x04,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_351, 2, (MRB_SYM(k), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_351 = {
  3,10,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_351,
  NULL,NULL,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_351,
  NULL,					/* debug_info */
  32,0,0,0,0
};
static const mrb_irep *gem_mrblib_mruby_hash_ext_proc_reps_18[1] = {
  &gem_mrblib_mruby_hash_ext_proc_irep_351,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_18, 5, (MRB_SYM_Q(block_given), MRB_SYM(transform_values), MRB_SYM(to_enum), MRB_SYM(keys), MRB_SYM(each), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_18[38] = {
0x39,0x00,0x00,0x01,0x01,0x02,0x01,0x30,0x04,0x00,0x27,0x04,0x00,0x09,0x10,0x05,0x01,0x2f,0x04,0x02,
0x01,0x3d,0x04,0x5e,0x03,0x00,0x30,0x04,0x03,0x62,0x05,0x00,0x34,0x04,0x04,0x00,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_18, 3, (0,MRB_SYM(b), MRB_SYM(hash), ), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_18 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_18,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_18,gem_mrblib_mruby_hash_ext_proc_reps_18,
  gem_mrblib_mruby_hash_ext_proc_lv_18,
  NULL,					/* debug_info */
  38,0,5,1,0
};
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_372[30] = {
0x39,0x04,0x00,0x00,0x12,0x04,0x01,0x05,0x01,0x12,0x07,0x01,0x08,0x01,0x23,0x07,0x44,0x06,0x00,0x01,
0x36,0x06,0x01,0x01,0x03,0x06,0x25,0x04,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_372, 2, (MRB_SYM(k), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_372 = {
  3,10,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_372,
  NULL,NULL,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_372,
  NULL,					/* debug_info */
  30,0,0,0,0
};
static const mrb_irep *gem_mrblib_mruby_hash_ext_proc_reps_19[1] = {
  &gem_mrblib_mruby_hash_ext_proc_irep_372,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_19, 5, (MRB_SYM_Q(block_given), MRB_SYM_B(transform_values), MRB_SYM(to_enum), MRB_SYM(keys), MRB_SYM(each), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_19[34] = {
0x39,0x00,0x00,0x01,0x01,0x02,0x01,0x30,0x03,0x00,0x27,0x03,0x00,0x09,0x10,0x04,0x01,0x2f,0x03,0x02,
0x01,0x3d,0x03,0x30,0x03,0x03,0x62,0x04,0x00,0x34,0x03,0x04,0x00,0x3f,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_19, 2, (0,MRB_SYM(b), ), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_19 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_19,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_19,gem_mrblib_mruby_hash_ext_proc_reps_19,
  gem_mrblib_mruby_hash_ext_proc_lv_19,
  NULL,					/* debug_info */
  34,0,5,1,0
};
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_393[13] = {
0x39,0x04,0x00,0x00,0x12,0x03,0x01,0x04,0x01,0x23,0x03,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_393, 2, (MRB_SYM(x), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_393 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_393,
  NULL,NULL,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_393,
  NULL,					/* debug_info */
  13,0,0,0,0
};
static const mrb_irep *gem_mrblib_mruby_hash_ext_proc_reps_20[1] = {
  &gem_mrblib_mruby_hash_ext_proc_irep_393,
};
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_20[9] = {
0x39,0x00,0x00,0x00,0x61,0x02,0x00,0x3d,0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_20, 1, (0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_20 = {
  2,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_20,
  NULL,NULL,gem_mrblib_mruby_hash_ext_proc_reps_20,
  gem_mrblib_mruby_hash_ext_proc_lv_20,
  NULL,					/* debug_info */
  9,0,0,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_414, 1, (MRB_SYM(fetch), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_414[17] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x21,0x05,0x03,0x00,0x31,0x03,0x00,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_414, 2, (MRB_SYM(k), 0,), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_414 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_414,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_414,NULL,
  gem_mrblib_mruby_hash_ext_proc_lv_414,
  NULL,					/* debug_info */
  17,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_hash_ext_proc_reps_21[1] = {
  &gem_mrblib_mruby_hash_ext_proc_irep_414,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_21, 1, (MRB_SYM(map), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_21[19] = {
0x39,0x00,0x10,0x01,0x01,0x03,0x02,0x01,0x04,0x01,0x62,0x05,0x00,0x34,0x04,0x00,0x00,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_lv_21, 3, (MRB_SYM(keys), 0,MRB_SYM(block), ), const);
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_21 = {
  4,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_21,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_21,gem_mrblib_mruby_hash_ext_proc_reps_21,
  gem_mrblib_mruby_hash_ext_proc_lv_21,
  NULL,					/* debug_info */
  19,0,1,1,0
};
static const mrb_irep *gem_mrblib_mruby_hash_ext_proc_reps_1[20] = {
  &gem_mrblib_mruby_hash_ext_proc_irep_2,
  &gem_mrblib_mruby_hash_ext_proc_irep_3,
  &gem_mrblib_mruby_hash_ext_proc_irep_4,
  &gem_mrblib_mruby_hash_ext_proc_irep_5,
  &gem_mrblib_mruby_hash_ext_proc_irep_6,
  &gem_mrblib_mruby_hash_ext_proc_irep_7,
  &gem_mrblib_mruby_hash_ext_proc_irep_8,
  &gem_mrblib_mruby_hash_ext_proc_irep_9,
  &gem_mrblib_mruby_hash_ext_proc_irep_10,
  &gem_mrblib_mruby_hash_ext_proc_irep_11,
  &gem_mrblib_mruby_hash_ext_proc_irep_12,
  &gem_mrblib_mruby_hash_ext_proc_irep_13,
  &gem_mrblib_mruby_hash_ext_proc_irep_14,
  &gem_mrblib_mruby_hash_ext_proc_irep_15,
  &gem_mrblib_mruby_hash_ext_proc_irep_16,
  &gem_mrblib_mruby_hash_ext_proc_irep_17,
  &gem_mrblib_mruby_hash_ext_proc_irep_18,
  &gem_mrblib_mruby_hash_ext_proc_irep_19,
  &gem_mrblib_mruby_hash_ext_proc_irep_20,
  &gem_mrblib_mruby_hash_ext_proc_irep_21,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_1, 27, (MRB_SYM(each_pair), MRB_SYM(each), MRB_SYM_B(merge), MRB_SYM(update), MRB_SYM_B(compact), MRB_SYM(compact), MRB_SYM(fetch), MRB_SYM(delete_if), MRB_SYM(flatten), MRB_SYM(invert), MRB_SYM(keep_if), MRB_SYM(to_h), MRB_OPSYM(lt), MRB_OPSYM(le), MRB_OPSYM(gt), MRB_OPSYM(ge), MRB_SYM(dig), MRB_SYM(transform_keys), MRB_SYM_B(transform_keys), MRB_SYM(transform_values), MRB_SYM_B(transform_values), MRB_SYM(to_proc), MRB_SYM(fetch_values), MRB_SYM(filter), MRB_SYM(select), MRB_SYM_B(filter), MRB_SYM_B(select), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_1[93] = {
0x6d,0x00,0x01,0x6b,0x01,0x02,0x00,0x6d,0x03,0x02,0x6b,0x01,0x04,0x01,0x6b,0x01,0x05,0x02,0x6b,0x01,
0x06,0x03,0x6b,0x01,0x07,0x04,0x6b,0x01,0x08,0x05,0x6b,0x01,0x09,0x06,0x6b,0x01,0x0a,0x07,0x6b,0x01,
0x0b,0x08,0x6b,0x01,0x0c,0x09,0x6b,0x01,0x0d,0x0a,0x6b,0x01,0x0e,0x0b,0x6b,0x01,0x0f,0x0c,0x6b,0x01,
0x10,0x0d,0x6b,0x01,0x11,0x0e,0x6b,0x01,0x12,0x0f,0x6b,0x01,0x13,0x10,0x6b,0x01,0x14,0x11,0x6b,0x01,
0x15,0x12,0x6b,0x01,0x16,0x13,0x6d,0x17,0x18,0x6d,0x19,0x1a,0x40,};
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_1 = {
  1,2,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_1,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_1,gem_mrblib_mruby_hash_ext_proc_reps_1,
  NULL,					/* lv */
  NULL,					/* debug_info */
  93,0,27,20,0
};
static const mrb_irep *gem_mrblib_mruby_hash_ext_proc_reps_0[1] = {
  &gem_mrblib_mruby_hash_ext_proc_irep_1,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_hash_ext_proc_syms_0, 1, (MRB_SYM(Hash), ), const);
static const mrb_code gem_mrblib_mruby_hash_ext_proc_iseq_0[13] = {
0x11,0x01,0x11,0x02,0x67,0x01,0x00,0x69,0x01,0x00,0x3d,0x01,0x76,};
static const mrb_irep gem_mrblib_mruby_hash_ext_proc_irep_0 = {
  1,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_hash_ext_proc_iseq_0,
  NULL,gem_mrblib_mruby_hash_ext_proc_syms_0,gem_mrblib_mruby_hash_ext_proc_reps_0,
  NULL,					/* lv */
  NULL,					/* debug_info */
  13,0,1,1,0
};
static
const struct RProc gem_mrblib_mruby_hash_ext_proc[] = {{
NULL,MRB_TT_PROC,MRB_GC_RED,MRB_OBJ_IS_FROZEN,0,{&gem_mrblib_mruby_hash_ext_proc_irep_0},NULL,{NULL},
}};
static void
gem_mrblib_mruby_hash_ext_proc_init_syms(mrb_state *mrb)
{
}
void mrb_mruby_hash_ext_gem_init(mrb_state *mrb);
void mrb_mruby_hash_ext_gem_final(mrb_state *mrb);

void GENERATED_TMP_mrb_mruby_hash_ext_gem_init(mrb_state *mrb) {
  gem_mrblib_mruby_hash_ext_proc_init_syms(mrb);
  mrb_mruby_hash_ext_gem_init(mrb);
  mrb_load_proc(mrb, gem_mrblib_mruby_hash_ext_proc);
}

void GENERATED_TMP_mrb_mruby_hash_ext_gem_final(mrb_state *mrb) {
  mrb_mruby_hash_ext_gem_final(mrb);
}
