/*
 * This file is loading the irep
 * Ruby GEM code.
 *
 * This file was generated by mruby/lib/mruby/gem.rb.
 *
 * IMPORTANT:
 *   This file was generated!
 *   All manual changes will get lost.
 */
#include <stdlib.h>
#include <mruby.h>
#include <mruby/irep.h>
#include <mruby/debug.h>
#include <mruby/proc.h>

#define mrb_BRACED(...) {__VA_ARGS__}
#define mrb_DEFINE_SYMS_VAR(name, len, syms, qualifier) \
  static qualifier mrb_sym name[len] = mrb_BRACED syms

static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_3[12] = {
0x39,0x00,0x00,0x00,0x12,0x02,0x06,0x03,0x4d,0x02,0x3d,0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_3, 1, (0,), const);
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_3 = {
  2,5,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_3,
  NULL,NULL,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_3,
  NULL,					/* debug_info */
  12,0,0,0,0
};
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_4[23] = {
0x39,0x00,0x00,0x00,0x12,0x02,0x06,0x03,0x4d,0x02,0x28,0x02,0x00,0x05,0x11,0x02,0x26,0x00,0x02,0x12,
0x02,0x3d,0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_4, 1, (0,), const);
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_4 = {
  2,5,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_4,
  NULL,NULL,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_4,
  NULL,					/* debug_info */
  23,0,0,0,0
};
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_5[12] = {
0x39,0x00,0x00,0x00,0x12,0x02,0x06,0x03,0x50,0x02,0x3d,0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_5, 1, (0,), const);
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_5 = {
  2,5,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_5,
  NULL,NULL,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_5,
  NULL,					/* debug_info */
  12,0,0,0,0
};
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_6[12] = {
0x39,0x00,0x00,0x00,0x12,0x02,0x06,0x03,0x4e,0x02,0x3d,0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_6, 1, (0,), const);
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_6 = {
  2,5,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_6,
  NULL,NULL,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_6,
  NULL,					/* debug_info */
  12,0,0,0,0
};
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_7[5] = {
0x39,0x00,0x00,0x00,0x42,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_7, 1, (0,), const);
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_7 = {
  2,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_7,
  NULL,NULL,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_7,
  NULL,					/* debug_info */
  5,0,0,0,0
};
static const mrb_irep *gem_mrblib_mruby_numeric_ext_proc_reps_1[5] = {
  &gem_mrblib_mruby_numeric_ext_proc_irep_3,
  &gem_mrblib_mruby_numeric_ext_proc_irep_4,
  &gem_mrblib_mruby_numeric_ext_proc_irep_5,
  &gem_mrblib_mruby_numeric_ext_proc_irep_6,
  &gem_mrblib_mruby_numeric_ext_proc_irep_7,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_syms_1, 5, (MRB_SYM_Q(zero), MRB_SYM_Q(nonzero), MRB_SYM_Q(positive), MRB_SYM_Q(negative), MRB_SYM_Q(integer), ), const);
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_1[22] = {
0x6b,0x01,0x00,0x00,0x6b,0x01,0x01,0x01,0x6b,0x01,0x02,0x02,0x6b,0x01,0x03,0x03,0x6b,0x01,0x04,0x04,
0x3d,0x00,};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_1 = {
  1,1,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_1,
  NULL,gem_mrblib_mruby_numeric_ext_proc_syms_1,gem_mrblib_mruby_numeric_ext_proc_reps_1,
  NULL,					/* lv */
  NULL,					/* debug_info */
  22,0,5,5,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_syms_30, 1, (MRB_OPSYM(and), ), const);
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_30[18] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x2f,0x03,0x00,0x01,0x01,0x04,0x01,0x4d,0x03,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_30, 2, (MRB_SYM(mask), 0,), const);
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_30 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_30,
  NULL,gem_mrblib_mruby_numeric_ext_proc_syms_30,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_30,
  NULL,					/* debug_info */
  18,0,1,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_syms_31, 2, (MRB_OPSYM(and), MRB_OPSYM(neq), ), const);
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_31[19] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x2f,0x03,0x00,0x01,0x06,0x04,0x32,0x03,0x01,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_31, 2, (MRB_SYM(mask), 0,), const);
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_31 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_31,
  NULL,gem_mrblib_mruby_numeric_ext_proc_syms_31,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_31,
  NULL,					/* debug_info */
  19,0,2,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_syms_32, 1, (MRB_OPSYM(and), ), const);
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_32[17] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x2f,0x03,0x00,0x01,0x06,0x04,0x4d,0x03,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_32, 2, (MRB_SYM(mask), 0,), const);
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_32 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_32,
  NULL,gem_mrblib_mruby_numeric_ext_proc_syms_32,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_32,
  NULL,					/* debug_info */
  17,0,1,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_syms_33, 2, (MRB_OPSYM(minus), MRB_SYM(div), ), const);
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_33[21] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x32,0x04,0x00,0x00,0x2f,0x03,0x01,0x01,0x32,0x03,0x00,0x00,0x3d,
0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_33, 2, (MRB_SYM(other), 0,), const);
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_33 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_33,
  NULL,gem_mrblib_mruby_numeric_ext_proc_syms_33,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_33,
  NULL,					/* debug_info */
  21,0,2,0,0
};
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_34[5] = {
0x39,0x00,0x00,0x00,0x41,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_34, 1, (0,), const);
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_34 = {
  2,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_34,
  NULL,NULL,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_34,
  NULL,					/* debug_info */
  5,0,0,0,0
};
static const mrb_irep *gem_mrblib_mruby_numeric_ext_proc_reps_2[5] = {
  &gem_mrblib_mruby_numeric_ext_proc_irep_30,
  &gem_mrblib_mruby_numeric_ext_proc_irep_31,
  &gem_mrblib_mruby_numeric_ext_proc_irep_32,
  &gem_mrblib_mruby_numeric_ext_proc_irep_33,
  &gem_mrblib_mruby_numeric_ext_proc_irep_34,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_syms_2, 5, (MRB_SYM_Q(allbits), MRB_SYM_Q(anybits), MRB_SYM_Q(nobits), MRB_SYM(ceildiv), MRB_SYM_Q(integer), ), const);
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_2[22] = {
0x6b,0x01,0x00,0x00,0x6b,0x01,0x01,0x01,0x6b,0x01,0x02,0x02,0x6b,0x01,0x03,0x03,0x6b,0x01,0x04,0x04,
0x3d,0x01,};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_2 = {
  1,2,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_2,
  NULL,gem_mrblib_mruby_numeric_ext_proc_syms_2,gem_mrblib_mruby_numeric_ext_proc_reps_2,
  NULL,					/* lv */
  NULL,					/* debug_info */
  22,0,5,5,0
};
static const mrb_irep *gem_mrblib_mruby_numeric_ext_proc_reps_0[2] = {
  &gem_mrblib_mruby_numeric_ext_proc_irep_1,
  &gem_mrblib_mruby_numeric_ext_proc_irep_2,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_syms_0, 2, (MRB_SYM(Numeric), MRB_SYM(Integer), ), const);
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_0[23] = {
0x11,0x01,0x11,0x02,0x67,0x01,0x00,0x69,0x01,0x00,0x11,0x01,0x11,0x02,0x67,0x01,0x01,0x69,0x01,0x01,
0x3d,0x01,0x76,};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_0 = {
  1,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_0,
  NULL,gem_mrblib_mruby_numeric_ext_proc_syms_0,gem_mrblib_mruby_numeric_ext_proc_reps_0,
  NULL,					/* lv */
  NULL,					/* debug_info */
  23,0,2,2,0
};
static
const struct RProc gem_mrblib_mruby_numeric_ext_proc[] = {{
NULL,MRB_TT_PROC,MRB_GC_RED,MRB_OBJ_IS_FROZEN,0,{&gem_mrblib_mruby_numeric_ext_proc_irep_0},NULL,{NULL},
}};
static void
gem_mrblib_mruby_numeric_ext_proc_init_syms(mrb_state *mrb)
{
}
void mrb_mruby_numeric_ext_gem_init(mrb_state *mrb);
void mrb_mruby_numeric_ext_gem_final(mrb_state *mrb);

void GENERATED_TMP_mrb_mruby_numeric_ext_gem_init(mrb_state *mrb) {
  gem_mrblib_mruby_numeric_ext_proc_init_syms(mrb);
  mrb_mruby_numeric_ext_gem_init(mrb);
  mrb_load_proc(mrb, gem_mrblib_mruby_numeric_ext_proc);
}

void GENERATED_TMP_mrb_mruby_numeric_ext_gem_final(mrb_state *mrb) {
  mrb_mruby_numeric_ext_gem_final(mrb);
}
