/*
 * This file is loading the irep
 * Ruby GEM code.
 *
 * This file was generated by mruby/lib/mruby/gem.rb.
 *
 * IMPORTANT:
 *   This file was generated!
 *   All manual changes will get lost.
 */
#include <stdlib.h>
#include <mruby.h>
#include <mruby/irep.h>
#include <mruby/debug.h>
#include <mruby/proc.h>

#define mrb_BRACED(...) {__VA_ARGS__}
#define mrb_DEFINE_SYMS_VAR(name, len, syms, qualifier) \
  static qualifier mrb_sym name[len] = mrb_BRACED syms

mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_symbol_ext_proc_syms_2, 3, (MRB_SYM(to_s), MRB_SYM_B(capitalize), MRB_SYM(to_sym), ), const);
static const mrb_code gem_mrblib_mruby_symbol_ext_proc_iseq_2[21] = {
0x39,0x00,0x00,0x00,0x30,0x02,0x00,0x33,0x02,0x01,0x27,0x02,0x00,0x02,0x12,0x02,0x33,0x02,0x02,0x3d,
0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_symbol_ext_proc_lv_2, 1, (0,), const);
static const mrb_irep gem_mrblib_mruby_symbol_ext_proc_irep_2 = {
  2,4,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_symbol_ext_proc_iseq_2,
  NULL,gem_mrblib_mruby_symbol_ext_proc_syms_2,NULL,
  gem_mrblib_mruby_symbol_ext_proc_lv_2,
  NULL,					/* debug_info */
  21,0,3,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_symbol_ext_proc_syms_3, 3, (MRB_SYM(to_s), MRB_SYM_B(downcase), MRB_SYM(to_sym), ), const);
static const mrb_code gem_mrblib_mruby_symbol_ext_proc_iseq_3[21] = {
0x39,0x00,0x00,0x00,0x30,0x02,0x00,0x33,0x02,0x01,0x27,0x02,0x00,0x02,0x12,0x02,0x33,0x02,0x02,0x3d,
0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_symbol_ext_proc_lv_3, 1, (0,), const);
static const mrb_irep gem_mrblib_mruby_symbol_ext_proc_irep_3 = {
  2,4,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_symbol_ext_proc_iseq_3,
  NULL,gem_mrblib_mruby_symbol_ext_proc_syms_3,NULL,
  gem_mrblib_mruby_symbol_ext_proc_lv_3,
  NULL,					/* debug_info */
  21,0,3,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_symbol_ext_proc_syms_4, 3, (MRB_SYM(to_s), MRB_SYM_B(upcase), MRB_SYM(to_sym), ), const);
static const mrb_code gem_mrblib_mruby_symbol_ext_proc_iseq_4[21] = {
0x39,0x00,0x00,0x00,0x30,0x02,0x00,0x33,0x02,0x01,0x27,0x02,0x00,0x02,0x12,0x02,0x33,0x02,0x02,0x3d,
0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_symbol_ext_proc_lv_4, 1, (0,), const);
static const mrb_irep gem_mrblib_mruby_symbol_ext_proc_irep_4 = {
  2,4,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_symbol_ext_proc_iseq_4,
  NULL,gem_mrblib_mruby_symbol_ext_proc_syms_4,NULL,
  gem_mrblib_mruby_symbol_ext_proc_lv_4,
  NULL,					/* debug_info */
  21,0,3,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_symbol_ext_proc_syms_5, 6, (MRB_SYM(Symbol), MRB_SYM_Q(kind_of), MRB_SYM(to_s), MRB_SYM_B(upcase), MRB_SYM(upcase), MRB_OPSYM(cmp), ), const);
static const mrb_code gem_mrblib_mruby_symbol_ext_proc_iseq_5[55] = {
0x39,0x04,0x00,0x00,0x01,0x05,0x01,0x1d,0x06,0x00,0x32,0x05,0x01,0x01,0x27,0x05,0x00,0x01,0x40,0x30,
0x05,0x02,0x01,0x03,0x05,0x01,0x05,0x03,0x33,0x05,0x03,0x01,0x05,0x01,0x33,0x05,0x02,0x33,0x05,0x04,
0x01,0x04,0x05,0x01,0x05,0x03,0x01,0x06,0x04,0x32,0x05,0x05,0x01,0x3d,0x05,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_symbol_ext_proc_lv_5, 4, (MRB_SYM(other), 0,MRB_SYM(lhs), MRB_SYM(rhs), ), const);
static const mrb_irep gem_mrblib_mruby_symbol_ext_proc_irep_5 = {
  5,8,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_symbol_ext_proc_iseq_5,
  NULL,gem_mrblib_mruby_symbol_ext_proc_syms_5,NULL,
  gem_mrblib_mruby_symbol_ext_proc_lv_5,
  NULL,					/* debug_info */
  55,0,6,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_symbol_ext_proc_syms_6, 1, (MRB_SYM(casecmp), ), const);
static const mrb_code gem_mrblib_mruby_symbol_ext_proc_iseq_6[34] = {
0x39,0x04,0x00,0x00,0x01,0x05,0x01,0x2f,0x04,0x00,0x01,0x01,0x03,0x04,0x01,0x04,0x03,0x29,0x04,0x00,
0x03,0x26,0x00,0x01,0x40,0x01,0x04,0x03,0x06,0x05,0x4d,0x04,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_symbol_ext_proc_lv_6, 3, (MRB_SYM(sym), 0,MRB_SYM(c), ), const);
static const mrb_irep gem_mrblib_mruby_symbol_ext_proc_irep_6 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_symbol_ext_proc_iseq_6,
  NULL,gem_mrblib_mruby_symbol_ext_proc_syms_6,NULL,
  gem_mrblib_mruby_symbol_ext_proc_lv_6,
  NULL,					/* debug_info */
  34,0,1,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_symbol_ext_proc_syms_7, 1, (MRB_SYM(length), ), const);
static const mrb_code gem_mrblib_mruby_symbol_ext_proc_iseq_7[13] = {
0x39,0x00,0x00,0x00,0x30,0x02,0x00,0x06,0x03,0x4d,0x02,0x3d,0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_symbol_ext_proc_lv_7, 1, (0,), const);
static const mrb_irep gem_mrblib_mruby_symbol_ext_proc_irep_7 = {
  2,5,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_symbol_ext_proc_iseq_7,
  NULL,gem_mrblib_mruby_symbol_ext_proc_syms_7,NULL,
  gem_mrblib_mruby_symbol_ext_proc_lv_7,
  NULL,					/* debug_info */
  13,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_symbol_ext_proc_reps_1[6] = {
  &gem_mrblib_mruby_symbol_ext_proc_irep_2,
  &gem_mrblib_mruby_symbol_ext_proc_irep_3,
  &gem_mrblib_mruby_symbol_ext_proc_irep_4,
  &gem_mrblib_mruby_symbol_ext_proc_irep_5,
  &gem_mrblib_mruby_symbol_ext_proc_irep_6,
  &gem_mrblib_mruby_symbol_ext_proc_irep_7,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_symbol_ext_proc_syms_1, 10, (MRB_SYM(Comparable), MRB_SYM(include), MRB_SYM(intern), MRB_SYM(to_sym), MRB_SYM(capitalize), MRB_SYM(downcase), MRB_SYM(upcase), MRB_SYM(casecmp), MRB_SYM_Q(casecmp), MRB_SYM_Q(empty), ), const);
static const mrb_code gem_mrblib_mruby_symbol_ext_proc_iseq_1[36] = {
0x1d,0x02,0x00,0x2f,0x01,0x01,0x01,0x6d,0x02,0x03,0x6b,0x01,0x04,0x00,0x6b,0x01,0x05,0x01,0x6b,0x01,
0x06,0x02,0x6b,0x01,0x07,0x03,0x6b,0x01,0x08,0x04,0x6b,0x01,0x09,0x05,0x3d,0x01,};
static const mrb_irep gem_mrblib_mruby_symbol_ext_proc_irep_1 = {
  1,4,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_symbol_ext_proc_iseq_1,
  NULL,gem_mrblib_mruby_symbol_ext_proc_syms_1,gem_mrblib_mruby_symbol_ext_proc_reps_1,
  NULL,					/* lv */
  NULL,					/* debug_info */
  36,0,10,6,0
};
static const mrb_irep *gem_mrblib_mruby_symbol_ext_proc_reps_0[1] = {
  &gem_mrblib_mruby_symbol_ext_proc_irep_1,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_symbol_ext_proc_syms_0, 1, (MRB_SYM(Symbol), ), const);
static const mrb_code gem_mrblib_mruby_symbol_ext_proc_iseq_0[13] = {
0x11,0x01,0x11,0x02,0x67,0x01,0x00,0x69,0x01,0x00,0x3d,0x01,0x76,};
static const mrb_irep gem_mrblib_mruby_symbol_ext_proc_irep_0 = {
  1,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_symbol_ext_proc_iseq_0,
  NULL,gem_mrblib_mruby_symbol_ext_proc_syms_0,gem_mrblib_mruby_symbol_ext_proc_reps_0,
  NULL,					/* lv */
  NULL,					/* debug_info */
  13,0,1,1,0
};
static
const struct RProc gem_mrblib_mruby_symbol_ext_proc[] = {{
NULL,MRB_TT_PROC,MRB_GC_RED,MRB_OBJ_IS_FROZEN,0,{&gem_mrblib_mruby_symbol_ext_proc_irep_0},NULL,{NULL},
}};
static void
gem_mrblib_mruby_symbol_ext_proc_init_syms(mrb_state *mrb)
{
}
void mrb_mruby_symbol_ext_gem_init(mrb_state *mrb);
void mrb_mruby_symbol_ext_gem_final(mrb_state *mrb);

void GENERATED_TMP_mrb_mruby_symbol_ext_gem_init(mrb_state *mrb) {
  gem_mrblib_mruby_symbol_ext_proc_init_syms(mrb);
  mrb_mruby_symbol_ext_gem_init(mrb);
  mrb_load_proc(mrb, gem_mrblib_mruby_symbol_ext_proc);
}

void GENERATED_TMP_mrb_mruby_symbol_ext_gem_final(mrb_state *mrb) {
  mrb_mruby_symbol_ext_gem_final(mrb);
}
