/*
 * This file is loading the irep
 * Ruby GEM code.
 *
 * This file was generated by mruby/lib/mruby/gem.rb.
 *
 * IMPORTANT:
 *   This file was generated!
 *   All manual changes will get lost.
 */
#include <stdlib.h>
#include <mruby.h>
#include <mruby/irep.h>
#include <mruby/debug.h>
#include <mruby/proc.h>

#define mrb_BRACED(...) {__VA_ARGS__}
#define mrb_DEFINE_SYMS_VAR(name, len, syms, qualifier) \
  static qualifier mrb_sym name[len] = mrb_BRACED syms

mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_19, 2, (MRB_SYM(call), MRB_SYM(add), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_19[21] = {
0x39,0x04,0x00,0x00,0x21,0x04,0x03,0x00,0x01,0x05,0x01,0x32,0x04,0x00,0x01,0x2f,0x03,0x01,0x01,0x3d,
0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_19, 2, (MRB_SYM(_1), 0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_19 = {
  3,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_19,
  NULL,gem_mrblib_mruby_set_proc_syms_19,NULL,
  gem_mrblib_mruby_set_proc_lv_19,
  NULL,					/* debug_info */
  21,0,2,0,0
};
static const mrb_irep *gem_mrblib_mruby_set_proc_reps_2[1] = {
  &gem_mrblib_mruby_set_proc_irep_19,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_2, 3, (MRB_SYM(__init), MRB_SYM(__do_with_enum), MRB_SYM(merge), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_2[57] = {
0x39,0x00,0x20,0x01,0x26,0x00,0x03,0x26,0x00,0x02,0x11,0x01,0x01,0x03,0x02,0x30,0x04,0x00,0x01,0x04,
0x01,0x29,0x04,0x00,0x03,0x26,0x00,0x01,0x3f,0x01,0x04,0x03,0x28,0x04,0x00,0x0d,0x01,0x05,0x01,0x62,
0x06,0x00,0x31,0x04,0x01,0x01,0x26,0x00,0x07,0x01,0x05,0x01,0x2f,0x04,0x02,0x01,0x3f,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_2, 3, (MRB_SYM(enum), 0,MRB_SYM(block), ), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_2 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_2,
  NULL,gem_mrblib_mruby_set_proc_syms_2,gem_mrblib_mruby_set_proc_reps_2,
  gem_mrblib_mruby_set_proc_lv_2,
  NULL,					/* debug_info */
  57,0,3,1,0
};
static const mrb_irep_pool gem_mrblib_mruby_set_proc_pool_3[1] = {
{IREP_TT_SSTR|(24<<2), {"\x76\x61\x6c\x75\x65\x20\x6d\x75\x73\x74\x20\x62\x65\x20\x65\x6e\x75\x6d\x65\x72\x61\x62\x6c\x65"}},
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_3, 4, (MRB_SYM(each), MRB_SYM_Q(respond_to), MRB_SYM(ArgumentError), MRB_SYM(raise), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_3[46] = {
0x39,0x04,0x00,0x01,0x01,0x03,0x02,0x01,0x04,0x01,0x10,0x05,0x00,0x32,0x04,0x01,0x01,0x28,0x04,0x00,
0x0d,0x01,0x04,0x01,0x01,0x05,0x03,0x34,0x04,0x00,0x00,0x26,0x00,0x0a,0x1d,0x05,0x02,0x5c,0x06,0x00,
0x2f,0x04,0x03,0x02,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_3, 3, (MRB_SYM(enum), 0,MRB_SYM(block), ), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_3 = {
  4,8,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_3,
  gem_mrblib_mruby_set_proc_pool_3,gem_mrblib_mruby_set_proc_syms_3,NULL,
  gem_mrblib_mruby_set_proc_lv_3,
  NULL,					/* debug_info */
  46,1,4,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_54, 1, (MRB_SYM(add), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_54[13] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x2f,0x03,0x00,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_54, 2, (MRB_SYM(o), 0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_54 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_54,
  NULL,gem_mrblib_mruby_set_proc_syms_54,NULL,
  gem_mrblib_mruby_set_proc_lv_54,
  NULL,					/* debug_info */
  13,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_set_proc_reps_4[1] = {
  &gem_mrblib_mruby_set_proc_irep_54,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_4, 2, (MRB_SYM(__merge), MRB_SYM(__do_with_enum), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_4[26] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x2f,0x03,0x00,0x01,0x27,0x03,0x00,0x0a,0x01,0x04,0x01,0x62,0x05,
0x00,0x31,0x03,0x01,0x01,0x3f,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_4, 2, (MRB_SYM(enum), 0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_4 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_4,
  NULL,gem_mrblib_mruby_set_proc_syms_4,gem_mrblib_mruby_set_proc_reps_4,
  gem_mrblib_mruby_set_proc_lv_4,
  NULL,					/* debug_info */
  26,0,2,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_5, 2, (MRB_SYM(clear), MRB_SYM(merge), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_5[16] = {
0x39,0x04,0x00,0x00,0x30,0x03,0x00,0x01,0x04,0x01,0x2f,0x03,0x01,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_5, 2, (MRB_SYM(enum), 0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_5 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_5,
  NULL,gem_mrblib_mruby_set_proc_syms_5,NULL,
  gem_mrblib_mruby_set_proc_lv_5,
  NULL,					/* debug_info */
  16,0,2,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_89, 1, (MRB_SYM(delete), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_89[13] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x2f,0x03,0x00,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_89, 2, (MRB_SYM(o), 0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_89 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_89,
  NULL,gem_mrblib_mruby_set_proc_syms_89,NULL,
  gem_mrblib_mruby_set_proc_lv_89,
  NULL,					/* debug_info */
  13,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_set_proc_reps_6[1] = {
  &gem_mrblib_mruby_set_proc_irep_89,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_6, 2, (MRB_SYM(__subtract), MRB_SYM(__do_with_enum), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_6[26] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x2f,0x03,0x00,0x01,0x27,0x03,0x00,0x0a,0x01,0x04,0x01,0x62,0x05,
0x00,0x31,0x03,0x01,0x01,0x3f,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_6, 2, (MRB_SYM(enum), 0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_6 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_6,
  NULL,gem_mrblib_mruby_set_proc_syms_6,gem_mrblib_mruby_set_proc_reps_6,
  gem_mrblib_mruby_set_proc_lv_6,
  NULL,					/* debug_info */
  26,0,2,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_107, 2, (MRB_SYM_Q(include), MRB_SYM(add), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_107[33] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x2f,0x03,0x00,0x01,0x28,0x03,0x00,0x0e,0x21,0x03,0x03,0x00,0x01,
0x04,0x01,0x32,0x03,0x01,0x01,0x26,0x00,0x02,0x11,0x03,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_107, 2, (MRB_SYM(o), 0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_107 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_107,
  NULL,gem_mrblib_mruby_set_proc_syms_107,NULL,
  gem_mrblib_mruby_set_proc_lv_107,
  NULL,					/* debug_info */
  33,0,2,0,0
};
static const mrb_irep *gem_mrblib_mruby_set_proc_reps_7[1] = {
  &gem_mrblib_mruby_set_proc_irep_107,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_7, 4, (MRB_SYM(__intersection), MRB_SYM(Set), MRB_SYM(new), MRB_SYM(__do_with_enum), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_7[39] = {
0x39,0x04,0x00,0x00,0x01,0x05,0x01,0x2f,0x04,0x00,0x01,0x27,0x04,0x00,0x16,0x1d,0x04,0x01,0x33,0x04,
0x02,0x01,0x03,0x04,0x01,0x05,0x01,0x62,0x06,0x00,0x31,0x04,0x03,0x01,0x01,0x04,0x03,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_7, 3, (MRB_SYM(enum), 0,MRB_SYM(n), ), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_7 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_7,
  NULL,gem_mrblib_mruby_set_proc_syms_7,gem_mrblib_mruby_set_proc_reps_7,
  gem_mrblib_mruby_set_proc_lv_7,
  NULL,					/* debug_info */
  39,0,4,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_8, 3, (MRB_SYM(__union), MRB_SYM(dup), MRB_SYM(merge), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_8[27] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x2f,0x03,0x00,0x01,0x27,0x03,0x00,0x0a,0x30,0x03,0x01,0x01,0x04,
0x01,0x32,0x03,0x02,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_8, 2, (MRB_SYM(enum), 0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_8 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_8,
  NULL,gem_mrblib_mruby_set_proc_syms_8,NULL,
  gem_mrblib_mruby_set_proc_lv_8,
  NULL,					/* debug_info */
  27,0,3,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_142, 1, (MRB_SYM(delete), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_142[17] = {
0x39,0x04,0x00,0x00,0x21,0x03,0x03,0x00,0x01,0x04,0x01,0x32,0x03,0x00,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_142, 2, (MRB_SYM(o), 0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_142 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_142,
  NULL,gem_mrblib_mruby_set_proc_syms_142,NULL,
  gem_mrblib_mruby_set_proc_lv_142,
  NULL,					/* debug_info */
  17,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_set_proc_reps_9[1] = {
  &gem_mrblib_mruby_set_proc_irep_142,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_9, 3, (MRB_SYM(__difference), MRB_SYM(dup), MRB_SYM(__do_with_enum), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_9[36] = {
0x39,0x04,0x00,0x00,0x01,0x05,0x01,0x2f,0x04,0x00,0x01,0x27,0x04,0x00,0x13,0x30,0x04,0x01,0x01,0x03,
0x04,0x01,0x05,0x01,0x62,0x06,0x00,0x31,0x04,0x02,0x01,0x01,0x04,0x03,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_9, 3, (MRB_SYM(enum), 0,MRB_SYM(result), ), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_9 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_9,
  NULL,gem_mrblib_mruby_set_proc_syms_9,gem_mrblib_mruby_set_proc_reps_9,
  gem_mrblib_mruby_set_proc_lv_9,
  NULL,					/* debug_info */
  36,0,3,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_10, 5, (MRB_SYM(__xor), MRB_SYM(Set), MRB_SYM(new), MRB_OPSYM(or), MRB_OPSYM(and), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_10[46] = {
0x39,0x04,0x00,0x00,0x01,0x05,0x01,0x2f,0x04,0x00,0x01,0x27,0x04,0x00,0x1d,0x1d,0x04,0x01,0x01,0x05,
0x01,0x32,0x04,0x02,0x01,0x01,0x03,0x04,0x01,0x05,0x03,0x2f,0x04,0x03,0x01,0x01,0x06,0x03,0x2f,0x05,
0x04,0x01,0x47,0x04,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_10, 3, (MRB_SYM(enum), 0,MRB_SYM(s2), ), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_10 = {
  4,8,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_10,
  NULL,gem_mrblib_mruby_set_proc_syms_10,NULL,
  gem_mrblib_mruby_set_proc_lv_10,
  NULL,					/* debug_info */
  46,0,5,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_11, 4, (MRB_SYM_Q(block_given), MRB_SYM(each), MRB_SYM(to_enum), MRB_SYM(to_a), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_11[34] = {
0x39,0x00,0x00,0x01,0x01,0x02,0x01,0x30,0x03,0x00,0x27,0x03,0x00,0x09,0x10,0x04,0x01,0x2f,0x03,0x02,
0x01,0x3d,0x03,0x30,0x03,0x03,0x01,0x04,0x02,0x34,0x03,0x01,0x00,0x3f,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_11, 2, (0,MRB_SYM(block), ), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_11 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_11,
  NULL,gem_mrblib_mruby_set_proc_syms_11,NULL,
  gem_mrblib_mruby_set_proc_lv_11,
  NULL,					/* debug_info */
  34,0,4,0,0
};
static const mrb_code gem_mrblib_mruby_set_proc_iseq_194[16] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x44,0x03,0x00,0x01,0x36,0x03,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_194, 2, (MRB_SYM(_1), 0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_194 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_194,
  NULL,NULL,NULL,
  gem_mrblib_mruby_set_proc_lv_194,
  NULL,					/* debug_info */
  16,0,0,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_195, 1, (MRB_SYM(delete), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_195[13] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x2f,0x03,0x00,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_195, 2, (MRB_SYM(_1), 0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_195 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_195,
  NULL,gem_mrblib_mruby_set_proc_syms_195,NULL,
  gem_mrblib_mruby_set_proc_lv_195,
  NULL,					/* debug_info */
  13,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_set_proc_reps_12[2] = {
  &gem_mrblib_mruby_set_proc_irep_194,
  &gem_mrblib_mruby_set_proc_irep_195,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_12, 5, (MRB_SYM_Q(block_given), MRB_SYM(delete_if), MRB_SYM(to_enum), MRB_SYM(select), MRB_SYM(each), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_12[35] = {
0x39,0x00,0x00,0x00,0x30,0x02,0x00,0x27,0x02,0x00,0x09,0x10,0x03,0x01,0x2f,0x02,0x02,0x01,0x3d,0x02,
0x62,0x03,0x00,0x31,0x02,0x03,0x00,0x62,0x03,0x01,0x34,0x02,0x04,0x00,0x3f,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_12, 1, (0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_12 = {
  2,5,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_12,
  NULL,gem_mrblib_mruby_set_proc_syms_12,gem_mrblib_mruby_set_proc_reps_12,
  gem_mrblib_mruby_set_proc_lv_12,
  NULL,					/* debug_info */
  35,0,5,2,0
};
static const mrb_code gem_mrblib_mruby_set_proc_iseq_215[16] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x44,0x03,0x00,0x01,0x36,0x03,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_215, 2, (MRB_SYM(_1), 0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_215 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_215,
  NULL,NULL,NULL,
  gem_mrblib_mruby_set_proc_lv_215,
  NULL,					/* debug_info */
  16,0,0,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_216, 1, (MRB_SYM(delete), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_216[13] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x2f,0x03,0x00,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_216, 2, (MRB_SYM(_1), 0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_216 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_216,
  NULL,gem_mrblib_mruby_set_proc_syms_216,NULL,
  gem_mrblib_mruby_set_proc_lv_216,
  NULL,					/* debug_info */
  13,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_set_proc_reps_13[2] = {
  &gem_mrblib_mruby_set_proc_irep_215,
  &gem_mrblib_mruby_set_proc_irep_216,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_13, 5, (MRB_SYM_Q(block_given), MRB_SYM(keep_if), MRB_SYM(to_enum), MRB_SYM(reject), MRB_SYM(each), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_13[35] = {
0x39,0x00,0x00,0x00,0x30,0x02,0x00,0x27,0x02,0x00,0x09,0x10,0x03,0x01,0x2f,0x02,0x02,0x01,0x3d,0x02,
0x62,0x03,0x00,0x31,0x02,0x03,0x00,0x62,0x03,0x01,0x34,0x02,0x04,0x00,0x3f,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_13, 1, (0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_13 = {
  2,5,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_13,
  NULL,gem_mrblib_mruby_set_proc_syms_13,gem_mrblib_mruby_set_proc_reps_13,
  gem_mrblib_mruby_set_proc_lv_13,
  NULL,					/* debug_info */
  35,0,5,2,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_236, 1, (MRB_OPSYM(lshift), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_236[24] = {
0x39,0x04,0x00,0x00,0x21,0x03,0x02,0x00,0x01,0x05,0x01,0x44,0x04,0x00,0x01,0x36,0x04,0x01,0x32,0x03,
0x00,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_236, 2, (MRB_SYM(_1), 0,), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_236 = {
  3,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_236,
  NULL,gem_mrblib_mruby_set_proc_syms_236,NULL,
  gem_mrblib_mruby_set_proc_lv_236,
  NULL,					/* debug_info */
  24,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_set_proc_reps_14[1] = {
  &gem_mrblib_mruby_set_proc_irep_236,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_14, 7, (MRB_SYM_Q(block_given), MRB_SYM_B(collect), MRB_SYM(to_enum), MRB_SYM(class), MRB_SYM(new), MRB_SYM(each), MRB_SYM(replace), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_14[45] = {
0x39,0x00,0x00,0x00,0x30,0x03,0x00,0x27,0x03,0x00,0x09,0x10,0x04,0x01,0x2f,0x03,0x02,0x01,0x3d,0x03,
0x30,0x03,0x03,0x33,0x03,0x04,0x01,0x02,0x03,0x62,0x04,0x00,0x31,0x03,0x05,0x00,0x01,0x04,0x02,0x2f,
0x03,0x06,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_14, 2, (0,MRB_SYM(set), ), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_14 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_14,
  NULL,gem_mrblib_mruby_set_proc_syms_14,gem_mrblib_mruby_set_proc_reps_14,
  gem_mrblib_mruby_set_proc_lv_14,
  NULL,					/* debug_info */
  45,0,7,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_15, 5, (MRB_SYM_Q(block_given), MRB_SYM_B(reject), MRB_SYM(to_enum), MRB_SYM(size), MRB_SYM(delete_if), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_15[57] = {
0x39,0x00,0x00,0x01,0x01,0x02,0x01,0x30,0x04,0x00,0x27,0x04,0x00,0x09,0x10,0x05,0x01,0x2f,0x04,0x02,
0x01,0x3d,0x04,0x30,0x04,0x03,0x01,0x03,0x04,0x01,0x05,0x02,0x31,0x04,0x04,0x00,0x30,0x04,0x03,0x01,
0x05,0x03,0x4d,0x04,0x28,0x04,0x00,0x05,0x11,0x04,0x26,0x00,0x02,0x12,0x04,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_15, 3, (0,MRB_SYM(block), MRB_SYM(n), ), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_15 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_15,
  NULL,gem_mrblib_mruby_set_proc_syms_15,NULL,
  gem_mrblib_mruby_set_proc_lv_15,
  NULL,					/* debug_info */
  57,0,5,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_16, 5, (MRB_SYM_Q(block_given), MRB_SYM_B(select), MRB_SYM(to_enum), MRB_SYM(size), MRB_SYM(keep_if), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_16[57] = {
0x39,0x00,0x00,0x01,0x01,0x02,0x01,0x30,0x04,0x00,0x27,0x04,0x00,0x09,0x10,0x05,0x01,0x2f,0x04,0x02,
0x01,0x3d,0x04,0x30,0x04,0x03,0x01,0x03,0x04,0x01,0x05,0x02,0x31,0x04,0x04,0x00,0x30,0x04,0x03,0x01,
0x05,0x03,0x4d,0x04,0x28,0x04,0x00,0x05,0x11,0x04,0x26,0x00,0x02,0x12,0x04,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_16, 3, (0,MRB_SYM(block), MRB_SYM(n), ), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_16 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_16,
  NULL,gem_mrblib_mruby_set_proc_syms_16,NULL,
  gem_mrblib_mruby_set_proc_lv_16,
  NULL,					/* debug_info */
  57,0,5,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_288, 3, (MRB_SYM(class), MRB_SYM(new), MRB_SYM(add), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_288[60] = {
0x39,0x04,0x00,0x00,0x01,0x05,0x01,0x44,0x04,0x00,0x01,0x36,0x04,0x01,0x01,0x03,0x04,0x21,0x04,0x02,
0x00,0x01,0x05,0x03,0x23,0x04,0x27,0x04,0x00,0x15,0x30,0x04,0x00,0x33,0x04,0x01,0x21,0x05,0x02,0x00,
0x01,0x06,0x03,0x01,0x07,0x04,0x01,0x04,0x07,0x25,0x05,0x01,0x05,0x01,0x32,0x04,0x02,0x01,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_288, 3, (MRB_SYM(i), 0,MRB_SYM(x), ), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_288 = {
  4,9,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_288,
  NULL,gem_mrblib_mruby_set_proc_syms_288,NULL,
  gem_mrblib_mruby_set_proc_lv_288,
  NULL,					/* debug_info */
  60,0,3,0,0
};
static const mrb_irep *gem_mrblib_mruby_set_proc_reps_17[1] = {
  &gem_mrblib_mruby_set_proc_irep_288,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_17, 4, (MRB_SYM_Q(block_given), MRB_SYM(classify), MRB_SYM(to_enum), MRB_SYM(each), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_17[32] = {
0x39,0x00,0x00,0x00,0x30,0x03,0x00,0x27,0x03,0x00,0x09,0x10,0x04,0x01,0x2f,0x03,0x02,0x01,0x3d,0x03,
0x5e,0x02,0x00,0x62,0x04,0x00,0x31,0x03,0x03,0x00,0x3d,0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_17, 2, (0,MRB_SYM(h), ), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_17 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_17,
  NULL,gem_mrblib_mruby_set_proc_syms_17,gem_mrblib_mruby_set_proc_reps_17,
  gem_mrblib_mruby_set_proc_lv_17,
  NULL,					/* debug_info */
  32,0,4,1,0
};
static const mrb_irep_pool gem_mrblib_mruby_set_proc_pool_18[1] = {
{IREP_TT_SSTR|(49<<2), {"\x53\x65\x74\x23\x64\x69\x76\x69\x64\x65\x20\x77\x69\x74\x68\x20\x32\x20\x61\x72\x69\x74\x79\x20\x62\x6c\x6f\x63\x6b\x20\x69\x73\x20\x6e\x6f\x74\x20\x69\x6d\x70\x6c\x65\x6d\x65\x6e\x74\x65\x64\x2e"}},
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_18, 10, (MRB_SYM_Q(block_given), MRB_SYM(divide), MRB_SYM(to_enum), MRB_SYM(arity), MRB_SYM(NotImplementedError), MRB_SYM(raise), MRB_SYM(Set), MRB_SYM(classify), MRB_SYM(values), MRB_SYM(new), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_18[66] = {
0x39,0x00,0x00,0x01,0x01,0x02,0x01,0x30,0x03,0x00,0x27,0x03,0x00,0x09,0x10,0x04,0x01,0x2f,0x03,0x02,
0x01,0x3d,0x03,0x01,0x03,0x02,0x33,0x03,0x03,0x08,0x04,0x4d,0x03,0x28,0x03,0x00,0x0a,0x1d,0x04,0x04,
0x5c,0x05,0x00,0x2f,0x03,0x05,0x02,0x1d,0x03,0x06,0x01,0x05,0x02,0x31,0x04,0x07,0x00,0x33,0x04,0x08,
0x32,0x03,0x09,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_lv_18, 2, (0,MRB_SYM(func), ), const);
static const mrb_irep gem_mrblib_mruby_set_proc_irep_18 = {
  3,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_18,
  gem_mrblib_mruby_set_proc_pool_18,gem_mrblib_mruby_set_proc_syms_18,NULL,
  gem_mrblib_mruby_set_proc_lv_18,
  NULL,					/* debug_info */
  66,1,10,0,0
};
static const mrb_irep *gem_mrblib_mruby_set_proc_reps_1[17] = {
  &gem_mrblib_mruby_set_proc_irep_2,
  &gem_mrblib_mruby_set_proc_irep_3,
  &gem_mrblib_mruby_set_proc_irep_4,
  &gem_mrblib_mruby_set_proc_irep_5,
  &gem_mrblib_mruby_set_proc_irep_6,
  &gem_mrblib_mruby_set_proc_irep_7,
  &gem_mrblib_mruby_set_proc_irep_8,
  &gem_mrblib_mruby_set_proc_irep_9,
  &gem_mrblib_mruby_set_proc_irep_10,
  &gem_mrblib_mruby_set_proc_irep_11,
  &gem_mrblib_mruby_set_proc_irep_12,
  &gem_mrblib_mruby_set_proc_irep_13,
  &gem_mrblib_mruby_set_proc_irep_14,
  &gem_mrblib_mruby_set_proc_irep_15,
  &gem_mrblib_mruby_set_proc_irep_16,
  &gem_mrblib_mruby_set_proc_irep_17,
  &gem_mrblib_mruby_set_proc_irep_18,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_1, 23, (MRB_SYM(initialize), MRB_SYM(__do_with_enum), MRB_SYM(merge), MRB_SYM(replace), MRB_SYM(subtract), MRB_SYM(intersection), MRB_OPSYM(and), MRB_SYM(union), MRB_OPSYM(or), MRB_OPSYM(add), MRB_SYM(difference), MRB_OPSYM(sub), MRB_OPSYM(xor), MRB_SYM(each), MRB_SYM(delete_if), MRB_SYM(keep_if), MRB_SYM_B(collect), MRB_SYM_B(map), MRB_SYM_B(reject), MRB_SYM_B(select), MRB_SYM_B(filter), MRB_SYM(classify), MRB_SYM(divide), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_1[88] = {
0x6b,0x01,0x00,0x00,0x6b,0x01,0x01,0x01,0x6b,0x01,0x02,0x02,0x6b,0x01,0x03,0x03,0x6b,0x01,0x04,0x04,
0x6b,0x01,0x05,0x05,0x6d,0x06,0x05,0x6b,0x01,0x07,0x06,0x6d,0x08,0x07,0x6d,0x09,0x07,0x6b,0x01,0x0a,
0x07,0x6d,0x0b,0x0a,0x6b,0x01,0x0c,0x08,0x6b,0x01,0x0d,0x09,0x6b,0x01,0x0e,0x0a,0x6b,0x01,0x0f,0x0b,
0x6b,0x01,0x10,0x0c,0x6d,0x11,0x10,0x6b,0x01,0x12,0x0d,0x6b,0x01,0x13,0x0e,0x6d,0x14,0x13,0x6b,0x01,
0x15,0x0f,0x6b,0x01,0x16,0x10,0x3d,0x01,};
static const mrb_irep gem_mrblib_mruby_set_proc_irep_1 = {
  1,2,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_1,
  NULL,gem_mrblib_mruby_set_proc_syms_1,gem_mrblib_mruby_set_proc_reps_1,
  NULL,					/* lv */
  NULL,					/* debug_info */
  88,0,23,17,0
};
static const mrb_irep *gem_mrblib_mruby_set_proc_reps_0[1] = {
  &gem_mrblib_mruby_set_proc_irep_1,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_set_proc_syms_0, 1, (MRB_SYM(Set), ), const);
static const mrb_code gem_mrblib_mruby_set_proc_iseq_0[13] = {
0x11,0x01,0x11,0x02,0x67,0x01,0x00,0x69,0x01,0x00,0x3d,0x01,0x76,};
static const mrb_irep gem_mrblib_mruby_set_proc_irep_0 = {
  1,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_set_proc_iseq_0,
  NULL,gem_mrblib_mruby_set_proc_syms_0,gem_mrblib_mruby_set_proc_reps_0,
  NULL,					/* lv */
  NULL,					/* debug_info */
  13,0,1,1,0
};
static
const struct RProc gem_mrblib_mruby_set_proc[] = {{
NULL,MRB_TT_PROC,MRB_GC_RED,MRB_OBJ_IS_FROZEN,0,{&gem_mrblib_mruby_set_proc_irep_0},NULL,{NULL},
}};
static void
gem_mrblib_mruby_set_proc_init_syms(mrb_state *mrb)
{
}
void mrb_mruby_set_gem_init(mrb_state *mrb);
void mrb_mruby_set_gem_final(mrb_state *mrb);

void GENERATED_TMP_mrb_mruby_set_gem_init(mrb_state *mrb) {
  gem_mrblib_mruby_set_proc_init_syms(mrb);
  mrb_mruby_set_gem_init(mrb);
  mrb_load_proc(mrb, gem_mrblib_mruby_set_proc);
}

void GENERATED_TMP_mrb_mruby_set_gem_final(mrb_state *mrb) {
  mrb_mruby_set_gem_final(mrb);
}
