#!/usr/bin/env python3
"""Embed a TTF font as a C header (byte array + length) with provenance.

Used to generate ttf/src/grapple_debug_font.h from ProggyClean.ttf.
Deterministic: identical input bytes produce an identical header.

Usage: embed_font.py <font.ttf> <out.h> <array_name>
"""

from __future__ import annotations

import sys
from pathlib import Path

HEADER = """\
/*
 * {name} — embedded debug font for Grapple_RenderDebugText.
 *
 * Font:       ProggyClean.ttf by Tristan Grimmer (proggyfonts.net)
 * Source:     https://github.com/bluescan/proggyfonts
 *             (ProggyOriginal/ProggyClean.ttf, master branch)
 * SHA-256:    {sha}
 * License:    MIT — reproduced below as required.
 *
 * MIT License
 *
 * Copyright (c) 2004, 2005 Tristan Grimmer
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * Generated by scripts/embed_font.py — do not edit by hand.
 */

"""


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2
    src, out, name = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3]
    data = src.read_bytes()
    import hashlib

    sha = hashlib.sha256(data).hexdigest()
    lines = [HEADER.format(name=name, sha=sha)]
    lines.append(f"static const unsigned char {name}[] = {{\n")
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        lines.append(f"    {chunk},\n")
    lines.append("};\n")
    lines.append(f"static const unsigned int {name}_len = {len(data)}u;\n")
    out.write_text("".join(lines))
    print(f"wrote {out} ({len(data)} bytes embedded, sha256 {sha[:16]}…)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
