#!/usr/bin/env python3
"""Embed GLSL sources into C headers.

Shaders are source code, and a game should not have to ship loose .glsl
files next to its binary — so the GLSL is compiled into the executable as
string literals. This generates those headers; the results are committed, so
building the project needs no Python.

Two modules have shaders, and they are embedded the same way:

    light/shaders/   -> light/src/light_shaders.h
    engine/shaders/  -> engine/src/post_shaders.h

Regenerate after editing any shader:

    python3 scripts/embed_shaders.py

`tests/light` and `tests/engine` check the committed headers still match the
sources, the same way bindgen_freshness guards the generated bindings.
"""
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


@dataclass(frozen=True)
class Bundle:
    """One shader directory and the header it becomes."""

    source_dir: Path
    output: Path
    guard: str
    blurb: str


BUNDLES = (
    Bundle(
        source_dir=REPO / "light" / "shaders",
        output=REPO / "light" / "src" / "light_shaders.h",
        guard="GRAPPLE_LIGHT_SHADERS_H",
        blurb="The GLSL sources in light/shaders/ as string literals, so a game ships\n"
        " * one binary with no shader files beside it.",
    ),
    Bundle(
        source_dir=REPO / "engine" / "shaders",
        output=REPO / "engine" / "src" / "post_shaders.h",
        guard="GRAPPLE_ENGINE_POST_SHADERS_H",
        blurb="The GLSL sources in engine/shaders/ as string literals: the\n"
        " * post-processing chain that bloom, CRT, chromatic aberration and FXAA\n"
        " * are made of.",
    ),
)


def header(bundle: Bundle) -> str:
    return f"""/*
 * {bundle.output.name} — GENERATED by scripts/embed_shaders.py. Do not edit.
 *
 * {bundle.blurb}
 *
 * The sources carry no #version line: the loader prepends one, because the
 * same shader has to serve desktop GL (120) and GLES/WebGL (100).
 */
#ifndef {bundle.guard}
#define {bundle.guard}

"""


def escape(line: str) -> str:
    return line.replace("\\", "\\\\").replace('"', '\\"')


def read_lines(path: Path) -> list[str]:
    # Bytes, not text: a Windows checkout may have CRLF line endings, and
    # the committed header has to compare equal on every platform.
    text = path.read_bytes().replace(b"\r\n", b"\n").decode("utf-8")
    return text.split("\n")


def emit(name: str, path: Path) -> str:
    out = [f"static const char {name}[] =\n"]
    lines = read_lines(path)
    if lines and lines[-1] == "":
        lines.pop()  # trailing newline, not a blank line
    for line in lines:
        out.append(f'    "{escape(line)}\\n"\n')
    out.append("    ;\n")
    return "".join(out)


def build(bundle: Bundle) -> str:
    parts = [header(bundle)]
    for path in sorted(bundle.source_dir.iterdir()):
        if path.suffix not in (".vert", ".frag"):
            continue
        name = "k" + "".join(p.title() for p in path.stem.split("_")) + path.suffix.title()[1:]
        # as_posix(): a Windows path renders with backslashes, which would
        # make the committed header differ there and nowhere else.
        parts.append(f"/* {path.relative_to(REPO).as_posix()} */\n")
        parts.append(emit(name, path))
        parts.append("\n")
    parts.append(f"\n#endif /* {bundle.guard} */\n")
    return "".join(parts)


def main() -> int:
    check = "--check" in sys.argv
    stale = 0
    for bundle in BUNDLES:
        fresh = build(bundle).encode("utf-8")
        name = bundle.output.name
        if check:
            current = (
                bundle.output.read_bytes().replace(b"\r\n", b"\n")
                if bundle.output.exists()
                else b""
            )
            if current != fresh:
                print(f"{name} is stale; run scripts/embed_shaders.py", file=sys.stderr)
                stale += 1
            else:
                print(f"{name} is up to date")
            continue
        # newline="" so the LF above survives on Windows too.
        with bundle.output.open("w", encoding="utf-8", newline="") as handle:
            handle.write(fresh.decode("utf-8"))
        print(f"wrote {bundle.output.relative_to(REPO)}")
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
