#!/usr/bin/env python3
"""Pack a game asset folder for Grapple::VFS.

Pipeline: folder -> deterministic zip -> optional SSE1 encryption (the same
container Grapple_EncryptData produces; mountable in C with
Grapple_MountEncryptedArchive) -> optional C header for embedding.

    pack_assets.py assets/ media.zip
    pack_assets.py assets/ media.bin --password "openSesame"
    pack_assets.py assets/ media.bin --password "pw" --header media.h --symbol game_media

The zip is deterministic (sorted entries, fixed timestamps), so repacking
unchanged assets yields byte-identical archives. The SSE1 encryption here is
an independent Python implementation of the C container (ChaCha20 RFC 8439,
PBKDF2-HMAC-SHA256, encrypt-then-MAC) — the C tests mount Python-encrypted
archives, which cross-validates both implementations.
"""

from __future__ import annotations

import argparse
import hashlib
import hmac
import io
import os
import struct
import sys
import zipfile
from pathlib import Path

PBKDF2_ITERATIONS = 10000


def build_zip(src: Path) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        files = sorted(p for p in src.rglob("*") if p.is_file())
        if not files:
            raise SystemExit(f"no files under {src}")
        for path in files:
            info = zipfile.ZipInfo(str(path.relative_to(src).as_posix()),
                                   date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            zf.writestr(info, path.read_bytes())
    return buf.getvalue()


def chacha20_xor(key: bytes, nonce: bytes, counter: int, data: bytes) -> bytes:
    def rotl(v: int, n: int) -> int:
        return ((v << n) | (v >> (32 - n))) & 0xFFFFFFFF

    def block(count: int) -> bytes:
        state = list(struct.unpack("<4I", b"expa" + b"nd 3" + b"2-by" + b"te k"))
        state += list(struct.unpack("<8I", key))
        state += [count] + list(struct.unpack("<3I", nonce))
        x = state[:]
        for _ in range(10):
            for a, b, c, d in ((0, 4, 8, 12), (1, 5, 9, 13), (2, 6, 10, 14),
                               (3, 7, 11, 15), (0, 5, 10, 15), (1, 6, 11, 12),
                               (2, 7, 8, 13), (3, 4, 9, 14)):
                x[a] = (x[a] + x[b]) & 0xFFFFFFFF
                x[d] = rotl(x[d] ^ x[a], 16)
                x[c] = (x[c] + x[d]) & 0xFFFFFFFF
                x[b] = rotl(x[b] ^ x[c], 12)
                x[a] = (x[a] + x[b]) & 0xFFFFFFFF
                x[d] = rotl(x[d] ^ x[a], 8)
                x[c] = (x[c] + x[d]) & 0xFFFFFFFF
                x[b] = rotl(x[b] ^ x[c], 7)
        return struct.pack("<16I", *((xi + si) & 0xFFFFFFFF for xi, si in zip(x, state)))

    out = bytearray()
    for i in range(0, len(data), 64):
        stream = block(counter + i // 64)
        chunk = data[i:i + 64]
        out += bytes(a ^ b for a, b in zip(chunk, stream))
    return bytes(out)


def encrypt_sse1(plain: bytes, password: str) -> bytes:
    salt = os.urandom(16)
    nonce = os.urandom(12)
    dk = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, PBKDF2_ITERATIONS, 64)
    ciphertext = chacha20_xor(dk[:32], nonce, 1, plain)
    body = b"SSE1" + salt + nonce + ciphertext
    tag = hmac.new(dk[32:], body, hashlib.sha256).digest()
    return body + tag


def emit_header(blob: bytes, symbol: str) -> str:
    lines = [f"/* Generated by scripts/pack_assets.py — {len(blob)} bytes. */",
             f"static const unsigned char {symbol}[] = {{"]
    for i in range(0, len(blob), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in blob[i:i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append(f"static const unsigned int {symbol}_len = {len(blob)}u;")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("source", type=Path, help="asset folder to pack")
    ap.add_argument("output", type=Path, help="output archive (zip or encrypted blob)")
    ap.add_argument("--password", help="encrypt the zip in the SSE1 container")
    ap.add_argument("--header", type=Path, help="also emit a C header embedding the output")
    ap.add_argument("--symbol", default="packed_assets", help="C symbol name for --header")
    args = ap.parse_args()

    blob = build_zip(args.source)
    print(f"packed {args.source}: {len(blob)} bytes (zip)")
    if args.password:
        blob = encrypt_sse1(blob, args.password)
        print(f"encrypted: {len(blob)} bytes (SSE1)")
    args.output.write_bytes(blob)
    print(f"wrote {args.output}")
    if args.header:
        args.header.write_text(emit_header(blob, args.symbol))
        print(f"wrote {args.header}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
