/* Original Grapple code (zlib). Compiled-in style JSON; edit files under styles/ then regenerate.
 */
#include "chip_style.h"

#include <SDL3/SDL.h>

static const char k_nes_smb[] =
    "{\n"
    "  \"schema\": 1,\n"
    "  \"id\": \"nes-smb\",\n"
    "  \"name\": \"NES (Super Mario Bros-inspired)\",\n"
    "  \"description\": \"Original Grapple synthesis inspired by typical use of this era's "
    "hardware. Not a recreation of any copyrighted soundtrack.\",\n"
    "  \"polyphony\": 4,\n"
    "  \"roles\": {\n"
    "    \"lead\": {\n"
    "      \"oscillator\": \"pulse25\",\n"
    "      \"pwm\": 0,\n"
    "      \"vibrato\": 0,\n"
    "      \"filter\": \"off\",\n"
    "      \"attack_ms\": 2,\n"
    "      \"decay_ms\": 80,\n"
    "      \"sustain\": 0.7,\n"
    "      \"release_ms\": 40,\n"
    "      \"level\": 0.22\n"
    "    },\n"
    "    \"harmony\": {\n"
    "      \"oscillator\": \"pulse50\",\n"
    "      \"pwm\": 0,\n"
    "      \"filter\": \"off\",\n"
    "      \"attack_ms\": 2,\n"
    "      \"decay_ms\": 90,\n"
    "      \"sustain\": 0.6,\n"
    "      \"release_ms\": 40,\n"
    "      \"level\": 0.16,\n"
    "      \"ring_ratio\": 0\n"
    "    },\n"
    "    \"bass\": {\n"
    "      \"oscillator\": \"triangle\",\n"
    "      \"triangle\": \"nes\",\n"
    "      \"filter\": \"off\",\n"
    "      \"attack_ms\": 1,\n"
    "      \"decay_ms\": 40,\n"
    "      \"sustain\": 1,\n"
    "      \"release_ms\": 20,\n"
    "      \"level\": 0.28\n"
    "    },\n"
    "    \"drums\": {\n"
    "      \"oscillator\": \"noise\",\n"
    "      \"filter\": \"off\",\n"
    "      \"drums\": \"none\",\n"
    "      \"attack_ms\": 1,\n"
    "      \"decay_ms\": 70,\n"
    "      \"sustain\": 0,\n"
    "      \"release_ms\": 30,\n"
    "      \"level\": 0.22,\n"
    "      \"share\": \"drums\"\n"
    "    },\n"
    "    \"noise\": {\n"
    "      \"oscillator\": \"noise\",\n"
    "      \"filter\": \"off\",\n"
    "      \"attack_ms\": 1,\n"
    "      \"decay_ms\": 50,\n"
    "      \"sustain\": 0,\n"
    "      \"level\": 0.18,\n"
    "      \"share\": \"drums\"\n"
    "    }\n"
    "  }\n"
    "}\n"
    "";

static const char k_gb_pokemon[] =
    "{\n"
    "  \"schema\": 1,\n"
    "  \"id\": \"gb-pokemon\",\n"
    "  \"name\": \"Game Boy (Pokemon-inspired)\",\n"
    "  \"description\": \"Original Grapple synthesis inspired by typical use of this era's "
    "hardware. Not a recreation of any copyrighted soundtrack.\",\n"
    "  \"polyphony\": 4,\n"
    "  \"roles\": {\n"
    "    \"lead\": {\n"
    "      \"oscillator\": \"pulse50\",\n"
    "      \"pwm\": 0,\n"
    "      \"vibrato\": 0.001,\n"
    "      \"vibrato_delay_ms\": 80,\n"
    "      \"filter\": \"off\",\n"
    "      \"attack_ms\": 4,\n"
    "      \"decay_ms\": 120,\n"
    "      \"sustain\": 0.75,\n"
    "      \"release_ms\": 60,\n"
    "      \"level\": 0.2\n"
    "    },\n"
    "    \"harmony\": {\n"
    "      \"oscillator\": \"pulse25\",\n"
    "      \"pwm\": 0,\n"
    "      \"filter\": \"off\",\n"
    "      \"attack_ms\": 6,\n"
    "      \"decay_ms\": 140,\n"
    "      \"sustain\": 0.65,\n"
    "      \"release_ms\": 80,\n"
    "      \"level\": 0.14,\n"
    "      \"ring_ratio\": 0\n"
    "    },\n"
    "    \"bass\": {\n"
    "      \"oscillator\": \"triangle\",\n"
    "      \"triangle\": \"nes\",\n"
    "      \"filter\": \"off\",\n"
    "      \"attack_ms\": 2,\n"
    "      \"decay_ms\": 60,\n"
    "      \"sustain\": 0.9,\n"
    "      \"release_ms\": 40,\n"
    "      \"level\": 0.24\n"
    "    },\n"
    "    \"drums\": {\n"
    "      \"oscillator\": \"noise\",\n"
    "      \"noise_metallic\": true,\n"
    "      \"filter\": \"off\",\n"
    "      \"drums\": \"none\",\n"
    "      \"attack_ms\": 1,\n"
    "      \"decay_ms\": 90,\n"
    "      \"sustain\": 0,\n"
    "      \"release_ms\": 40,\n"
    "      \"level\": 0.18,\n"
    "      \"share\": \"drums\"\n"
    "    },\n"
    "    \"noise\": {\n"
    "      \"oscillator\": \"noise\",\n"
    "      \"filter\": \"off\",\n"
    "      \"attack_ms\": 1,\n"
    "      \"decay_ms\": 60,\n"
    "      \"sustain\": 0,\n"
    "      \"level\": 0.16,\n"
    "      \"share\": \"drums\"\n"
    "    }\n"
    "  }\n"
    "}\n"
    "";

static const char k_genesis_sonic[] =
    "{\n"
    "  \"schema\": 1,\n"
    "  \"id\": \"genesis-sonic\",\n"
    "  \"name\": \"Genesis (Sonic-inspired)\",\n"
    "  \"description\": \"Original Grapple 2-operator FM inspired by typical use of this era's "
    "hardware. Not a recreation of any copyrighted soundtrack.\",\n"
    "  \"voice\": \"fm\",\n"
    "  \"approximation\": true,\n"
    "  \"polyphony\": 6,\n"
    "  \"roles\": {\n"
    "    \"lead\": {\n"
    "      \"voice\": \"fm\",\n"
    "      \"fm_index\": 2.4,\n"
    "      \"filter\": \"off\",\n"
    "      \"attack_ms\": 3,\n"
    "      \"decay_ms\": 180,\n"
    "      \"sustain\": 0.55,\n"
    "      \"release_ms\": 80,\n"
    "      \"level\": 0.2\n"
    "    },\n"
    "    \"harmony\": {\n"
    "      \"voice\": \"fm\",\n"
    "      \"fm_index\": 1.4,\n"
    "      \"filter\": \"off\",\n"
    "      \"attack_ms\": 8,\n"
    "      \"decay_ms\": 220,\n"
    "      \"sustain\": 0.5,\n"
    "      \"release_ms\": 120,\n"
    "      \"level\": 0.14,\n"
    "      \"ring_ratio\": 0\n"
    "    },\n"
    "    \"bass\": {\n"
    "      \"oscillator\": \"pulse50\",\n"
    "      \"filter\": \"svf_low\",\n"
    "      \"cutoff_hz\": 1800,\n"
    "      \"filter_env\": 0.4,\n"
    "      \"attack_ms\": 4,\n"
    "      \"decay_ms\": 100,\n"
    "      \"sustain\": 0.7,\n"
    "      \"release_ms\": 50,\n"
    "      \"level\": 0.28\n"
    "    },\n"
    "    \"drums\": {\n"
    "      \"oscillator\": \"noise\",\n"
    "      \"filter\": \"off\",\n"
    "      \"drums\": \"none\",\n"
    "      \"attack_ms\": 1,\n"
    "      \"decay_ms\": 80,\n"
    "      \"sustain\": 0,\n"
    "      \"release_ms\": 30,\n"
    "      \"level\": 0.22\n"
    "    }\n"
    "  }\n"
    "}\n"
    "";

static const char k_snes_zelda[] =
    "{\n"
    "  \"schema\": 1,\n"
    "  \"id\": \"snes-zelda\",\n"
    "  \"name\": \"SNES (Zelda-inspired)\",\n"
    "  \"description\": \"Original Grapple synthesis inspired by typical use of this era's "
    "hardware. Not a recreation of any copyrighted soundtrack.\",\n"
    "  \"approximation\": true,\n"
    "  \"polyphony\": 8,\n"
    "  \"roles\": {\n"
    "    \"lead\": {\n"
    "      \"oscillator\": \"pulse50\",\n"
    "      \"pwm\": 0.04,\n"
    "      \"vibrato\": 0.0015,\n"
    "      \"vibrato_delay_ms\": 160,\n"
    "      \"filter\": \"svf_low\",\n"
    "      \"cutoff_hz\": 5200,\n"
    "      \"attack_ms\": 8,\n"
    "      \"decay_ms\": 240,\n"
    "      \"sustain\": 0.7,\n"
    "      \"release_ms\": 180,\n"
    "      \"level\": 0.18,\n"
    "      \"effects\": { \"chorus\": 0.18, \"reverb\": 0.12 }\n"
    "    },\n"
    "    \"harmony\": {\n"
    "      \"mix\": { \"pulse\": 0.4, \"triangle\": 0.6 },\n"
    "      \"triangle\": \"analog\",\n"
    "      \"filter\": \"svf_low\",\n"
    "      \"cutoff_hz\": 3600,\n"
    "      \"attack_ms\": 18,\n"
    "      \"decay_ms\": 320,\n"
    "      \"sustain\": 0.65,\n"
    "      \"release_ms\": 240,\n"
    "      \"level\": 0.14,\n"
    "      \"ring_ratio\": 0,\n"
    "      \"effects\": { \"chorus\": 0.22, \"reverb\": 0.16 }\n"
    "    },\n"
    "    \"bass\": {\n"
    "      \"oscillator\": \"saw\",\n"
    "      \"filter\": \"svf_low\",\n"
    "      \"cutoff_hz\": 900,\n"
    "      \"filter_env\": 0.5,\n"
    "      \"attack_ms\": 6,\n"
    "      \"decay_ms\": 160,\n"
    "      \"sustain\": 0.8,\n"
    "      \"release_ms\": 120,\n"
    "      \"level\": 0.26\n"
    "    },\n"
    "    \"drums\": {\n"
    "      \"oscillator\": \"noise\",\n"
    "      \"filter\": \"svf_low\",\n"
    "      \"cutoff_hz\": 5000,\n"
    "      \"drums\": \"none\",\n"
    "      \"attack_ms\": 1,\n"
    "      \"decay_ms\": 110,\n"
    "      \"sustain\": 0,\n"
    "      \"release_ms\": 60,\n"
    "      \"level\": 0.2\n"
    "    }\n"
    "  }\n"
    "}\n"
    "";

static const char k_dos_wolf3d[] =
    "{\n"
    "  \"schema\": 1,\n"
    "  \"id\": \"dos-wolf3d\",\n"
    "  \"name\": \"MS-DOS (Wolfenstein 3D-inspired)\",\n"
    "  \"description\": \"Original Grapple 2-operator FM inspired by typical AdLib/OPL use. Not a "
    "recreation of any copyrighted soundtrack.\",\n"
    "  \"voice\": \"fm\",\n"
    "  \"approximation\": true,\n"
    "  \"polyphony\": 9,\n"
    "  \"roles\": {\n"
    "    \"lead\": {\n"
    "      \"voice\": \"fm\",\n"
    "      \"fm_index\": 3.2,\n"
    "      \"filter\": \"off\",\n"
    "      \"attack_ms\": 2,\n"
    "      \"decay_ms\": 90,\n"
    "      \"sustain\": 0.35,\n"
    "      \"release_ms\": 40,\n"
    "      \"level\": 0.22\n"
    "    },\n"
    "    \"harmony\": {\n"
    "      \"voice\": \"fm\",\n"
    "      \"fm_index\": 1.8,\n"
    "      \"filter\": \"off\",\n"
    "      \"attack_ms\": 4,\n"
    "      \"decay_ms\": 140,\n"
    "      \"sustain\": 0.4,\n"
    "      \"release_ms\": 70,\n"
    "      \"level\": 0.14,\n"
    "      \"ring_ratio\": 0\n"
    "    },\n"
    "    \"bass\": {\n"
    "      \"voice\": \"fm\",\n"
    "      \"fm_index\": 0.8,\n"
    "      \"filter\": \"off\",\n"
    "      \"attack_ms\": 3,\n"
    "      \"decay_ms\": 80,\n"
    "      \"sustain\": 0.6,\n"
    "      \"release_ms\": 40,\n"
    "      \"level\": 0.26\n"
    "    },\n"
    "    \"drums\": {\n"
    "      \"oscillator\": \"noise\",\n"
    "      \"filter\": \"off\",\n"
    "      \"drums\": \"none\",\n"
    "      \"attack_ms\": 1,\n"
    "      \"decay_ms\": 55,\n"
    "      \"sustain\": 0,\n"
    "      \"release_ms\": 20,\n"
    "      \"level\": 0.24\n"
    "    }\n"
    "  }\n"
    "}\n"
    "";

void Chip_RegisterBuiltinStyles(void)
{
    static const char *const docs[] = {
        k_nes_smb, k_gb_pokemon, k_genesis_sonic, k_snes_zelda, k_dos_wolf3d,
    };
    for (int i = 0; i < (int)(sizeof(docs) / sizeof(docs[0])); ++i)
    {
        Grapple_ChipStyle *style = Chip_ParseChipStyleJson(docs[i], SDL_strlen(docs[i]), true);
        if (style)
            Grapple_RegisterChipStyle(style);
    }
}
