option(GAME_SANITIZERS "Instrument game code with ASan and UBSan (Linux)" OFF)
function(game_warnings target)
  set_target_properties(${target} PROPERTIES C_STANDARD 17 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W4 /WX $<$<CONFIG:Release>:/Zi>)
    target_link_options(${target} PRIVATE $<$<CONFIG:Release>:/DEBUG>)
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Werror $<$<CONFIG:Release>:-g>)
  endif()
  if(GAME_SANITIZERS)
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" OR NOT CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
      message(FATAL_ERROR "GAME_SANITIZERS requires Linux with GCC or Clang")
    endif()
    target_compile_options(${target} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
    target_link_options(${target} PRIVATE -fsanitize=address,undefined)
  endif()
endfunction()
